### ISSUE TITLE
Minor typo (Release December 31, 2020)

### ISSUE THREAD

**Issue by wilfreddesert** [probml/pml-book#10]
Hi, there is a minor typo on page 753 (line 4) in the release as of December 31, 2020:

A basis $B$ is a set of lienarly...
Should be, of course, linearly :) 

Thank you for uploading the book! It's incredible. How often are you going to reupload the corrected version of the PDF?

**Comment by murphyk** [comment]
fixed. I will probably update the pdf 2-3 x per week at first, then less often after the deluge of initial typos is fixed.
