### ISSUE TITLE
Comments on section 15.4 Attention

### ISSUE THREAD

**Issue by danoneata** [probml/pml-book#100]
Version: May 6, 2021

Typos and minor fixes:
- Page 518, line -2: Braces are not balanced in the notation of the attention weights `α_{1:m}`.
- Page 519, second paragraph:
  - "large negative value, such as 10⁶" → missing a minus sign, "-10⁶".
  - "we can implement this efficient ..." → "efficiently".
- Page 519, last paragraph: "of a a density kernel" → repeating word.
- Page 520, equation (15.40): there are missing closing brackets, both in the numerator and denominator.
- Page 520, equation (15.41): should use _n_ (lower case) to denote the number of samples.
- Page 520, subsection 15.4.2: "for test input `j`" → "for test input `x_j^*`"?
- Page 521, equation (15.45): the values (for the attention layer) come from the encoder and should be denoted by the "e" superscript (that is, `h_i^e` instead of `h_i`).
- Page 522, "machibe translation" → "machine translation"
- Page 522, figure 15.19: it would be great if the font of the labels would be larger.
- Page 525, subsection 15.4.7: "in Fig. 15.22b" → "in Fig. 15.22"?

More subjective comments and suggestions:
- Page 518, first paragraph: maybe exemplify the standard neural network layer by using an _v_-dimensional vector at the output (that is, **z** = φ(W**v**)), in order to match the input and output dimensions of the attention layer.
- The entire section is using a notation like `α_i(q, {k_i})`, but the two occurrences of `i` have different meanings: the first one represents a fixed index, while the second is a (dummy) variable suggesting that `{k_i}` is a set: `{k_i} ≡ {k_1, k_2, ..., k_m}`.
- Section 15.4.4: I'm a bit confused by some of the notation regarding the decoder:
    - Page 521: shouldn't `f_d` also get as input the auto-regressive context (in this case, `y_{t-1}`)?
    - Page 522: it is mentioned that the context vector and the previously predicted token, `y_{t-1}`, are "fed into `h_t^d`", but I'm unclear on what that means exactly, since I expect the expression "fed into" to be followed by a function; maybe it should have been `f_d` instead of `h_t^d`?

**Comment by murphyk** [comment]
fixed, thansk a lot
