### ISSUE TITLE
Issues section 17.1.1 (Smoothness prior) Book 1 draft

### ISSUE THREAD

**Issue by hajlaouiyakin** [probml/pml-book#103]
In section 17.1.1 ( Smoothness prior) and 17.1.2 (Inference from noise-free observations) of the book, I noticed the following issues:
1) Equation (17.3) : <img src="https://render.githubusercontent.com/render/math?math=L^TL"> is not invertible because it is of rank <img src="https://render.githubusercontent.com/render/math?math=D-2 < D">
2) Equation (17.8) :  <img src="https://render.githubusercontent.com/render/math?math=L_1">  is not invertible because it is not a square matrix.

**Comment by murphyk** [comment]
Thanks, I added some clarifications.
