### ISSUE TITLE
7.1.2.4: Range and Nullspace, Fig 7.4

### ISSUE THREAD

**Issue by SantoshK-Singh** [probml/pml-book#105]
The beautiful & simple digram communicates that, When A is applied to vectors(R^n) then: 
On LHS:
- vectors in "outer box" map to a range,
- vectors in "inner box" i.e. zero-vector
However on the output/ RHS, both range and zero-vector are shown in the inner box. Then, what does the outer box represent?

Note: one explanation for the empty outer box that comes to mind is that, A maps vectors only to a subspace of R^m i.e. operation A does not span/ cover the entire R^m. If that's the case then, a side-note will be helpful for students.

Else, I would appreciate if can correct my misunderstanding.

**Comment by murphyk** [comment]
Yes, the outer box on the RHS is the unreachable part (ie codomain - range). I added a comment to the caption.
