### ISSUE TITLE
Small typos in Chapter 5 (May 6, 2021 version)

### ISSUE THREAD

**Issue by kskucheryavyy** [probml/pml-book#106]
**1. Section 5.1.3, Page 163:**
![image](https://user-images.githubusercontent.com/83252212/118591278-e3f46700-b7de-11eb-90ee-6dad5a523c7e.png)
"Instead" is two times

**2. Bold versus non-bold x in Chapter 5:**
I know this is a really tiny thing, but, maybe, for consistency, all x should be made bold in Chapter 5. In some expressions they are bold, like in expression (5.2):
![image](https://user-images.githubusercontent.com/83252212/118616449-aa325900-b7fc-11eb-9509-747938d5de42.png)
or expression (5.15):
![image](https://user-images.githubusercontent.com/83252212/118616573-c8985480-b7fc-11eb-8420-007213752fdd.png)
In other places they are in regular math font, like in the opening paragraph of Chapter 5:
![image](https://user-images.githubusercontent.com/83252212/118616695-e36ac900-b7fc-11eb-86d3-d89d167cff20.png)
or expression (5.1), which precedes expression (5.2):
![image](https://user-images.githubusercontent.com/83252212/118616802-fe3d3d80-b7fc-11eb-8719-97589142136c.png)
and here:
![image](https://user-images.githubusercontent.com/83252212/118616885-101ee080-b7fd-11eb-9d35-f2a2bcfc1bee.png)
and in other places in Chapter 5.

**Comment by murphyk** [comment]
fixed, thanks
