### ISSUE TITLE
Typos in chapter 7

### ISSUE THREAD

**Issue by jakobullmann** [probml/pml-book#107]
on page 223/ section 7.1.3.2 after eqn. (7.24): 'A' is missing under the square root.
on page 228/ section 7.1.5.3: "In Sec. 7.4.3.1, we show that a matrix is positive definite iff its eigenvalues are positive." This statement should be qualified: "we show that a **symmetric** matrix is positive definite iff its eigenvalues are positive"
on page 237/ section 7.3: "In this section, we discuss how to invert different kinds of **matrces**."

**Comment by murphyk** [comment]
fixed, thanks
