### ISSUE TITLE
Issues in chapter 8

### ISSUE THREAD

**Issue by jakobullmann** [probml/pml-book#108]
In section 8.5, p. 293 after eqn. (8.97): The equation C = I \cap E doesn't make sense to me... Is this perhaps some deliberate abuse of notation where I and E are given double meanings, to mean both the families of indices and the sets of points where the constraint is satisfied (note that the symbol C is already used)? Also the following remark in parentheses is unclear to me.
[ EDIT: I'm assuming C unintentionally got a double meaning there, plus I think it should be \cup rather than \cap ]

In section 8.5.2: After eqn. (8.111), the sign ofter the coefficient corresponding to the inequality constraints is changed from + to -. _However, this would imply that the Lagrangian would have to be minimized rather than maximized w.r.t. mu, which is not done._ (EDIT: this is not even true, because the inner minimum/infimum would already give negative infinity, so the outer minimum/infimum would be ill-defined) As a consequence, also the KKT conditions are stated with the wrong sign w.r.t. the inequality constraints (I also double-checked this with several optimization textbooks) [ EDIT: Nocedal-Wright states the KKT conditions like that, but they consider the constraint g >= 0 rather than g <= 0 ].

EDIT: I just noticed a more severe issue: The claim before eqn. (8.100), that the Lagrangian for an equality constraint should be minimized, is wrong because the minimum doesn't exist (the Lagrangian is unbounded below). Rather, a stationary point must be found.

**Comment by murphyk** [comment]
Thanks. So would it suffice to change g <= 0? Or do I need to change more?

**Comment by netw0rkf10w** [comment]
In (8.111) (and accordingly in all the subsequent equations), the sign before `mu_i` should be `+`, not `-`. One can keep `-` but then the constraint `mu >= 0` will have to be changed to `mu <= 0`, but this is not standard. I would go even further and recommend to use `+` for `lambda` as well for consistency (and for aesthetic reason), but of course this is not critical.

Another important issue is that the same symbol `\mathcal{L}` is being used for two different functions (at the same place): the objective function and the Lagrangian. That is mathematically not correct! (Imagine writing`f(x, y) = f(x) + yg(x)`, which doesn't make sense.) I would recommend to use the `L` in regular font for the Lagrangian (because `\mathcal{L}` is reserved for the loss function I guess), and to make this distinction clear in the text (via a footnote for example).

**Comment by jakobullmann** [comment]
@murphyk Yes, I think it would suffice to change to g >= 0.

I found another issue also in chapter 8. I will open a new issue for that.

**Comment by netw0rkf10w** [comment]
I would change the sign in the Lagrangian rather changing the constraint.

**Comment by jakobullmann** [comment]
Sorry, I have to correct my statement: If you change the sign to g >= 0, then g should be a concave function and not a convex function (at least for convex optimization problems).

So if you insist that a convex problem has a convex objective function and convex constraint functions, then the condition for the inequality constraints should read g <= 0 and the signs in the KKT condition/in the Lagrangian should all be +.

If you insist that the signs in the KKT condition/in the Lagrangian stay -, you have to change at least g to be a concave function.

(Either way, the Lagrangian will stay a convex function.)

**Comment by netw0rkf10w** [comment]
> So if you insist that a convex problem has a convex objective function and convex constraint functions, then the condition for the inequality constraints should read g <= 0 and **the signs in the KKT condition/in the Lagrangian should all be +**.
> 
> **If you insist that the signs in the KKT condition/in the Lagrangian stay -, you have to change at least g to be a concave function.**
> 
> (Either way, the Lagrangian will stay a convex function.)

Both your statements above (in boldface) are not correct. We can keep `g` convex while having `-` in the Lagrangian: it suffices to change the sign of `mu` (see my comment above).

**Comment by jakobullmann** [comment]
> > So if you insist that a convex problem has a convex objective function and convex constraint functions, then the condition for the inequality constraints should read g <= 0 and **the signs in the KKT condition/in the Lagrangian should all be +**.
> > **If you insist that the signs in the KKT condition/in the Lagrangian stay -, you have to change at least g to be a concave function.**
> > (Either way, the Lagrangian will stay a convex function.)
> 
> Both your statements above (in boldface) are not correct. We can keep `g` convex while having `-` in the Lagrangian: it suffices to change the sign of `mu` (see my comment above).

That's true. I considered the idea of mu having negative components to be so ugly and non-standard that it can be ignored, but of course that would be an option as well.

My point was mainly that the combination convex g + the condition g >= 0 will never define a convex optimization problem, since {x : g(x) >= 0} will generally be an unbounded concave set.

**Comment by netw0rkf10w** [comment]
That's why I said one shouldn't change the constraint ;)

**Comment by netw0rkf10w** [comment]
To summarize, the best option is to change the sign of `mu` to `+` in the Lagrangian, as I already suggested in my first comment above.

**Comment by murphyk** [comment]
Ok, I changed the symbol for Lagrangian to regular L (to avoid accidental clash with \mathcal{L}),
and changed sign of mu and lambda to +. Does everything look kosher now?

Adding my coauthor Mark, to double check.
@mark-schmidt

<img width="702" alt="Screen Shot 2021-05-27 at 10 51 17 PM" src="https://user-images.githubusercontent.com/4632336/119936465-19672600-bf3e-11eb-98ef-cdff17929fc3.png">

**Comment by netw0rkf10w** [comment]
Looks good to me.

**Comment by netw0rkf10w** [comment]
Clarification: The changes you made look good but there's still an issue (#116) after equation (17). I was in a hurry and didn't notice that the Slater part was included in the screenshot above, sorry about that.
