### ISSUE TITLE
l_{01} in sections 5.1.2.1 and 5.1.2.2

### ISSUE THREAD

**Issue by nsanghi** [probml/pml-book#114]
Ver: Draft of “Probabilistic Machine Learning: An Introduction”. May 6, 2021

A suggestion >

Section 5.1.2.1 defines zero-one loss as l_{01}(y*, /hat{y})

and section 5.1.2.2 defines l(h,h) = l_{a,h}, which for a=0 and h=1 can be confusing with zero-one loss symbol in 5.1.2.1. Could we use some other symbol in 5.1.2.2 to avoid this?

**Comment by murphyk** [comment]
fixed, thanks
