### ISSUE TITLE
Section 5.1.7 - use of p(D|m)

### ISSUE THREAD

**Issue by nsanghi** [probml/pml-book#115]
Ver: Draft of “Probabilistic Machine Learning: An Introduction”. May 6, 2021

Section 5.1.7 uses expression "log p(D|m)" which is not defined earlier. In fact conditioning on "m" in other expressions are not very clear till you read section 5.2.2. Would help if "p(D|m)" is explained in section 5.1.7 or a cross ref is made to 5.2.2

**Comment by murphyk** [comment]
Yes, sec 5.1.7  is actually in the wrong place, and will be moved to later, so this notation will be clearer.
(This was a latex accident)
