### ISSUE TITLE
Another issue in Chapter 8

### ISSUE THREAD

**Issue by netw0rkf10w** [probml/pml-book#116]
<img width="900" alt="Screen Shot 2021-05-22 at 16 30 23" src="https://user-images.githubusercontent.com/8569515/119230086-03f79380-bb1b-11eb-99ec-c5a88327cc6d.png">

To the best of my knowledge, the Slater's condition is only applicable to convex problems, i.e., `h` has to be **affine** in this context.

**Comment by murphyk** [comment]
Maybe Slater's condition is a red herring here? I'm just trying to state when KKT holds.
According to [wikipedia](https://en.wikipedia.org/wiki/Karush%E2%80%93Kuhn%E2%80%93Tucker_conditions), we require that f and g are convex. They do not mention restrictions on h...

**Comment by netw0rkf10w** [comment]
Sorry for the late reply, I had some important deadline. 

In general the KKT conditions only hold under some regularity assumption, which is also stated on Wikipedia:

<img width="1155" alt="kkt" src="https://user-images.githubusercontent.com/8569515/121561130-7cfe5280-ca18-11eb-828f-4b1850920282.png">

I am not aware of any necessary conditions for the case where `g` and `h` being convex are the only assumptions. If you were referring to this:

<img width="1168" alt="kkt_inequality" src="https://user-images.githubusercontent.com/8569515/121563930-32caa080-ca1b-11eb-91f2-46a1f6bb855f.png">

then this seems to be a mistake. The above only holds for inequality-constrained optimization (i.e., there's no `h`). In this case `f` needs not be convex.

(By the way, is it already mentioned somewhere in the text that `L`, `g`, and `h` are assumed to be continuously differentiable? This important assumption seems to have also been omitted.)
