### ISSUE TITLE
Hilbert spaces / RKHS

### ISSUE THREAD

**Issue by jakobullmann** [probml/pml-book#118]
The treatment of Hilbert spaces / RKHS is in my opinion problematic for several reasons:

- To start with, in 17.7.2 the space L^2 is non-rigorously defined as a space of functions rather than equivalence classes of measurable functions coinciding mu-almost everywhere. That's maybe not so critical by itself, as it's a technical detail that most readers won't care about. However, a consequence of this is that the evaluation functional cannot be defined just by mapping f to f(x), because f(x) will depend on the representative within the equivalence class [f]. Anyway, such a functional, even if it could be defined (let's say such as to map at least continuous functions f to f(x)), wouldn't be a *bounded/continuous* functional, except in the cases in which {x} is a mu-atom...
[ Example: For a Matern kernel, the RKHS will be a (fractional) Sobolev space, and the evaluation functional will be continuous with respect to the corresponding Sobolev norm. But it will not be continuous with respect to L^2, which is weaker than the Sobolov norm and therefore has fewer continuous functionals. ]

- ... in other words: L^2 will generally not be an RKHS anyway (I think the case in which H is the conjugate of an L^2 space under the Fourier transform is more interesting). 
- ... unlike L^2, an RKHS is rigorously a space of functions (not equivalence classes). Therefore, the introduction of section 17.7.3 "**Let H be the space L^2(X ) of functions X → R.** For each x ∈ X , let δx : H → R be the evaluation functional that takes as input a function f ∈ H and evaluates it at x, i.e., δx(f) = f(x). **We say that a Hilbert space H is a Reproducing Kernel Hilbert Space** or RKHS if ..." is problematic.

Other issues in section 17.7.3:
"Clearly the kernel function is symmetric. One can also show that it is positive semidefinite, in the sense that we can represent it as
K(x, y) = sum j≥1 λjψj (x)ψj (y) (17.139)
where λj is a countable sequence of non-negative numbers decreasing to 0, and the ψj are orthonormal
functions in L2(X ). This result is known as Mercer’s theorem."

- "_One can show that it is positive semidefinite, in the sense..._": I don't think "in the sense" is adequate there: On the one hand, I really don't see how this is synonymous (maybe that was supposed to allude to the spectral theorem for self-adjoint operators in linear algebra, but the functional analytic situation is much more complicated and only for compact self-adjoint operators there is a spectral theorem that looks similar to the linear algebraic one). On the other hand, it's a very general statement that the kernel is psd, but Mercer's theorem is rigorous only under some restrictive conditions (which are e.g. violated for a translation-invariant kernel on a space with infinite measure).
On the other hand, the fact that every RKHS has a psd kernel is more elementary. Therefore I wouldn't say it's a consequence of Mercer's theorem (although it's implied by Mercer's theorem when it holds).

- On the other hand, this decomposition in (17.139) actually holds with respect to some L^2 space on X. I think this should be emphasized because otherwise a reader could think that thi psi_j are orthonormal with respect to H.

Moreover:
In the paragraph after eqn. (17.132) there is a typo: **functiions**

**Comment by murphyk** [comment]
Thanks. If I send you the latex, can you rewrite this section properly for me, before the die is cast? (Send me an email...)
