### ISSUE TITLE
Typos and other small issues in Draft version May 6 2021.

### ISSUE THREAD

**Issue by asharakeh** [probml/pml-book#119]
Creating this issue to track small mistakes that do not necessarily require a separate issue by themselves. Owners feel free to remove this in case it is preferred to open a separate issue per typo.

**Comment by asharakeh** [comment]
Additional parentheses on Page 63, equation 2.148.

![image](https://user-images.githubusercontent.com/19838254/119516042-667fa800-bd44-11eb-93dc-adb4f8fb46e2.png)

**Comment by jmlipman** [comment]
Repeated sentence in Section 5.5.4

![image](https://user-images.githubusercontent.com/3540650/119870876-7f49b280-bf2a-11eb-8a80-bb80b0dfdbf8.png)

**Comment by zexisun** [comment]
Section 20.1.2.1, Equation (20.6), should be x_n

<img width="257" alt="Screenshot 2021-05-30 at 14 59 17" src="https://user-images.githubusercontent.com/42411119/120095287-bd77e980-c157-11eb-8451-54e60f317660.png">

**Comment by jmlipman** [comment]
![image](https://user-images.githubusercontent.com/3540650/120099454-32412880-c144-11eb-946f-e7e3ace07786.png)

**Comment by Hyunjin-Yoon** [comment]
Typo on 19.2.4.1 (Imputation tasks)
In this approacg, --> In this approach,

**Comment by Atarust** [comment]
Typo in 13.4.4  Residual connections
 it is earier to train ->  it is easier to train

**Comment by jmlipman** [comment]
![image](https://user-images.githubusercontent.com/3540650/121052339-f43aa900-c7c2-11eb-908d-5a47b1423831.png)

**Comment by jmlipman** [comment]
![image](https://user-images.githubusercontent.com/3540650/121054269-dc642480-c7c4-11eb-87b5-9d33253247f6.png)

**Comment by sriharsha0806** [comment]
Typo in 16.5.2 Proxy methods
The third paragraph, More recently, propoosed --> proposed

**Comment by murphyk** [comment]
fixed, thanks
