### ISSUE TITLE
In Eq 14.8 (Page 430), matrix W is not in Toeplitz form

### ISSUE THREAD

**Issue by tnnandi** [probml/pml-book#12]

**Comment by murphyk** [comment]
Good catch! I guess it's only Toeplitz in the 1d case?
eg compare
https://stats.stackexchange.com/questions/374716/cnn-is-this-a-toeplitz-matrix
to
https://stats.stackexchange.com/questions/411498/representation-of-a-convolutional-layer-as-a-fully-connected-one-matrix-represe

**Comment by murphyk** [comment]
fixed
