### ISSUE TITLE
Mahalanobis distance in terms of a linear mapping

### ISSUE THREAD

**Issue by cyugao** [probml/pml-book#122]
I am confused about this part on page 80:
> We can also define the Mahalanobis distance in terms of a linear mapping L such that Σ^{-1} = L'L, where L may map from R^D to R^d where d ≤ D.

Since Σ^{-1} is positive definite, L must have full rank; thus we always have d = D.

**Comment by danoneata** [comment]
Sorry to interject, but positive definiteness doesn't imply full rank, does it? For example, for any vector `u`, the matrix `M = u u'` has rank 1 and is positive definite: `v' M v = v' (u u') v = (v' u) (v' u)' = (v' u)² ≥ 0, ∀ v`. Or maybe I have misunderstood your point.

**Comment by cyugao** [comment]
> Sorry to interject, but positive definiteness doesn't imply full rank, does it? For example, for any vector `u`, the matrix `M = u u'` has rank 1 and is positive definite: `v' M v = v' (u u') v = (v' u) (v' u)' = (v' u)² ≥ 0, ∀ v`. Or maybe I have misunderstood your point.

`uu'` is positive semidefinite, but not positive definite.

**Comment by danoneata** [comment]
Thanks! You are of course right! 🙂 Maybe the claim can be loosen by saying that the Mahalanobis distance can be _approximated_ using a low-rank decomposition?

**Comment by murphyk** [comment]
yes, this is a good point. I think i will just remove the comment, since it is confusing (as written).
