### ISSUE TITLE
17.1 and 17.1.1 minor issues

### ISSUE THREAD

**Issue by JohnHBrock** [probml/pml-book#123]
From the 2021-05-21 release:

1. 17.1, page 565 typo: "unkown"
2. Both the end of 17.1 and the first paragraph of 17.1.1 (end of page 565/start of page 566) contain duplicate phrasing (maybe intentional?):
    > [...] the function by a list of function values on a grid of D points, we can perform inference with random vectors, instead of random functions. We generalize this to arbitrary input domains in Sec. 17.3.

**Comment by murphyk** [comment]
fixed, thanks
