### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by anfelor** [probml/pml-book#131]
Draft May 21. It's an amazing book and I can't wait to read further!

 - A.3.3 The softmax function is called `S(x)` but defined over `\alpha`.
 - The equation (7.231) holds for differentiable f, but not in general. In particular, it is not enough that the limes in the definition of `D_v f(x)` is defined at `x` (what a reader unfamiliar with the material might assume).
 - Equation 7.28 should say `E[v^T A^T A v]` I think
 - Under equation 7.204 you write `Hence we can first solve L_{nn} y_n = b_n to find y_n`. But shouldn't we start with `L_{11} y_1 = b_1`?

**Comment by murphyk** [comment]
thanks, fixed
