### ISSUE TITLE
Comments for Chapter 11 Linear regression Part 1 (May 6, 2021)

### ISSUE THREAD

**Issue by petercerno** [probml/pml-book#132]
Hi Kevin, I am sending my comments for Chapter 11 Linear regression (Part 1)

[cerno_comments_on_pmlv2_c11_linreg_part1.pdf](https://github.com/probml/pml-book/files/6637531/cerno_comments_on_pmlv2_c11_linreg_part1.pdf)

Thanks!

Cheers,

Peter

**Comment by murphyk** [comment]
fixed, thanks!
