### ISSUE TITLE
Comments for Chapter 11 Linear regression Part 2 (June 5, 2021)

### ISSUE THREAD

**Issue by petercerno** [probml/pml-book#134]
Hi Kevin, I am sending few remaining comments for Chapter 11 Linear regression (Part 2)

[cerno_comments_on_pmlv2_c11_linreg_part2.pdf](https://github.com/probml/pml-book/files/6747960/cerno_comments_on_pmlv2_c11_linreg_part2.pdf)

Thanks!

Cheers,

Peter

**Comment by murphyk** [comment]
very helpful, as usual - thanks!. All fixed now.
