### ISSUE TITLE
Eq 4.17 typo with additional 1/n

### ISSUE THREAD

**Issue by andreimargeloiu** [probml/pml-book#135]
When deriving the expected KL in eq 4.17, I believe there's a type with 1/N (see below). Why? Because the first expansion is for p_D(y | x), which is approximated as \delta(y - y_n). Equation 4.18 is still correct because p_D(x) brings the constant 1/N.

![894BFBFC-B8A7-4354-A5BE-86F55C2021EF](https://user-images.githubusercontent.com/18227298/124265568-86be3600-db3e-11eb-834f-71fc50c832bc.png)

**Comment by murphyk** [comment]
fixed
