### ISSUE TITLE
Eq 4.101

### ISSUE THREAD

**Issue by andreimargeloiu** [probml/pml-book#136]
The derivation of the MAP estimate of the Covariance of a Gaussian makes a subtle assumption (see image), that might not be true.

![image](https://user-images.githubusercontent.com/18227298/124359718-d7ad5780-dc2e-11eb-82aa-d3987939b97c.png)

However, that assumption doesn't seem to be true! I tried a small Python script which invalidates the assumption from the derivations. What am I missing?

```
import numpy as np

x1 = [-2.1, -1,  4.3]
x2 = [3,  1.1,  0.12]
X = np.stack((x1, x2), axis=0)

U, S, VT = np.linalg.svd(X, full_matrices=False)
D = np.diag(S)

Z = U @ D
Sigma_Z = np.cov(Z, bias=True)

print("Left side")
print(VT.T @ np.diag(np.diag(Sigma_Z)) @ VT)
print("Right side")
print(np.diag(np.diag(VT.T @ Sigma_Z @ VT)))
```

![7DB7AB2F-DF96-4AC4-824A-38AC952A5567](https://user-images.githubusercontent.com/18227298/124359853-65894280-dc2f-11eb-9dcd-567231d8adfd.png)

**Comment by murphyk** [comment]
yes i think you are right.  I removed that section.
