### ISSUE TITLE
Typos in Section 2?

### ISSUE THREAD

**Issue by shaneweisz** [probml/pml-book#137]
Draft June 5

Some potential typos I have picked up, forgive me if I’m mistaken:

* Should the definition in 2.6 be for *independent* or *unconditionally independent* events, not *conditionally independent* events?
* Similarly, in the paragraph preceding equation 2.16, for the situation when the joint of two variables can be represented as the product of the marginals, should this be for *independent* or *unconditionally independent* variables, rather than *conditionally independent* variables as written in the text?

Really enjoying the book!

**Comment by murphyk** [comment]
fixed, thanks!

**Comment by cleitonmoya** [comment]
Released Book

In section 2.1.3.5 (Independece of events, pg. 33) I think there is the same typo: it shouldn't be "event A is _independent_ or _unconditionally independent_ of event B"?

Also really enjoying the book!
