### ISSUE TITLE
Section 15.3.3 Inductive Bias

### ISSUE THREAD

**Issue by HunderlineK** [probml/pml-book#139]
In section 15.3.3 of Book 1, the paragraph describing the advantages of sinusoidal basis in self-attention reads:

> Second, nearby locations have similar encodings, which provides a useful form of inductive bias. In particular, we have pt+φ = f(pt), where f is a linear transformation

It might be my lack of understanding, but isn't `pt+φ = f(pt)` applicable regardless of whether the locations are nearby or not, and so is this part perhaps describing a third advantage rather than an instance of the second advantage (or a second but distinct instance of inductive bias)?

Thanks!

**Comment by murphyk** [comment]
fixed
