### ISSUE TITLE
2.8.5 The convolution theorem

### ISSUE THREAD

**Issue by masonlr** [probml/pml-book#142]
Thanks for the great resource!

For the "sum of two dice" example

<img width="1539" alt="image" src="https://user-images.githubusercontent.com/5828176/124478008-10dcf780-dde8-11eb-8780-f2574554f1c9.png">

I'm a bit confused by `The result, of course, is equal to the binomial distribution, Bin(y|2,(1/6,...,1/6)).` using a vector parameter `theta=(1/6,...,1/6)` given that the Binomial distribution is defined with scalar parameter `theta` in Eq. 2.68.

Also, the post here https://math.stackexchange.com/a/1204492 suggests that the result might be piecewise linear in `y`.

**Comment by murphyk** [comment]
fixed, thanks
