### ISSUE TITLE
Inconsistency among Figure 19.2 and its caption

### ISSUE THREAD

**Issue by JeanKaddour** [probml/pml-book#144]
In the Figure, it is said that the parameters of the hidden layers are fine-tuned on the target dataset; not frozen. 

![image](https://user-images.githubusercontent.com/11850255/124736518-fd787c00-df0e-11eb-9446-3763147bc631.png)

However, in the caption, it says 
![image](https://user-images.githubusercontent.com/11850255/124736649-20a32b80-df0f-11eb-9a90-61da66c646f5.png)

**Comment by murphyk** [comment]
fixed
