### ISSUE TITLE
Typo in 15.2

### ISSUE THREAD

**Issue by stella-gao** [probml/pml-book#145]
<img width="809" alt="Screen Shot 2021-07-07 at 10 08 31 PM" src="https://user-images.githubusercontent.com/16229161/124865963-79ef7700-df70-11eb-8890-2f5c6e526db4.png">

I think here in (15.18),
<img width="40" alt="Screen Shot 2021-07-07 at 10 11 31 PM" src="https://user-images.githubusercontent.com/16229161/124865939-6fcd7880-df70-11eb-95be-d49b00a110e9.png"> should be <img width="38" alt="Screen Shot 2021-07-07 at 10 11 36 PM" src="https://user-images.githubusercontent.com/16229161/124865882-54626d80-df70-11eb-972b-ac8eaada72c8.png">. Thanks!

**Comment by murphyk** [comment]
fixed
