### ISSUE TITLE
Possible error in Eqn. 17.24

### ISSUE THREAD

**Issue by InfProbSciX** [probml/pml-book#148]
Apologies if I'm missing something, but the following doesn't look right:

<img width="555" alt="Screenshot 2021-07-11 at 21 15 16" src="https://user-images.githubusercontent.com/32991292/125208874-17a6b700-e28d-11eb-9f78-8aac9176d8f0.png">

The periodic kernel is strictly positive, whereas the cosine kernel is not, so I don't understand how one recovers the cosine kernel in the limit. With the lengthscale tending to infinity, the periodic kernel should just become 1.

**Comment by murphyk** [comment]
fixed
