### ISSUE TITLE
MInor typos in Chapter 10

### ISSUE THREAD

**Issue by nsanghi** [probml/pml-book#154]
Ver: June 5, 2021

1) equation 10.22 expression has a shapek (1xD) - a row vecotr instead of a column vector. should the expression be trasposed to get the dimensions to (Dx1) - a column vector?

2) equation 10.66 - 2nd term on right. The summation over n is extra and incorrect. The whole sequence from 10.63 to 10.67 is about summing over classes C for a given example x_n. 

3) Also equasiton 10.63 the "NLL" on right side should have a subscript "n" to signify that it is a loss for nth example only.

4) Equation 10.68 - the shape of g(w) should match shape of W i.e. CxD . But RHS has a shape of DxC. RHS should be transposed to get it in the required shape of CxD

**Comment by murphyk** [comment]
Thank you! All fixed.
