### ISSUE TITLE
Comments for Part III Deep Neural Networks (June 5, 2021)

### ISSUE THREAD

**Issue by petercerno** [probml/pml-book#155]
Hi Kevin, I am sending some comments for Part III Deep Neural Networks

[cerno_comments_on_pmlv2_part_iii_dnns.pdf](https://github.com/probml/pml-book/files/6907095/cerno_comments_on_pmlv2_part_iii_dnns.pdf)

Thanks!

Cheers,

Peter

**Comment by murphyk** [comment]
very helpful, thank you!
