### ISSUE TITLE
Comments from Chapters 2, 3, 7

### ISSUE THREAD

**Issue by vihari** [probml/pml-book#156]
Apologies if they have been resolved already.
I am enjoying reading the book, thanks for this great resource. 

The comments are made using the following PDF (if in case the page numbers have changed): [Drive Link](https://drive.google.com/file/d/1XEr3CO8AhgRcxI20JOkPN8yNWRrELhWs/view?usp=sharing)
All the comments below are marked in the annotated PDF that I have attached. It should be easy to spot them given the page number. 
- Page 59: `The half Cauchy distribution is a version of the Cauchy (with mean 0)` But mean of Cauchy is not defined as stated in the preceding sentence. 
- Page 61: Eq. 2.142, the PDF should be expressed only in terms of a, s on RHS (It also has b).
- Page 74: Right after eq 3.7, we also need a>0 for corr[X, Y]=1
- Page 87: After Eq. 3.61, Some text missing in the para: `To formalize what we mean...`
- Page 222: Right before Eq. 7.21, do you mean `m\geq n` instead of m>n; "onto the range of A ~is~ as"
- Page 223: 0-norm satisfies triangle inequality but not homogeneity. 
- Page 225: Possible typo in Eq. 7.44, it is incorrect this form. Counter-example with any 2x2 matrix with non-zero non-diagonal entries. 
- Page 233: Eq. 7.79: In right most RHS, the non-diagonal entries are swapped. Top-right should have been `s1x_{1D}` instead. 
- Page 239: Text right before Eq. 7.121: The reference to Eq. 7.119 should have been Eq. 7.120 instead.
- Page 253: Text after Eq. 7.204. The text seems to have been written with upper triangle matrix in mind while talking about lower.

**Comment by murphyk** [comment]
very helpful, thanks
