### ISSUE TITLE
Typos in Chapter 3

### ISSUE THREAD

**Issue by stvhuang** [probml/pml-book#159]
1. P.80, Equation 3.17
For `\sigma`s' subscripts, consider using `x` and `y` instead of `1` and `2`.

1. P.87, Figure 3.8
In the caption, there are two **(a)** and the second one should be **(b)**.

1. P.87, The paragraph above Equation 3.58
`\mathbf\Sigma_y` should be `\Sigma_y`.

1. P.91, First line in Section 3.4.2
"... the Bernoulli distributio."
should be
"... the Bernoulli distributio**n**.".

1. P.91, Between Equation 3.76 and Equation 3.77
"... linear dependen**den**ce between ..."
should be
"... linear dependence between ...".

1. P.95, Figure 3.12
In the caption,
"... using K=3 clusters ..."
should be
"... using K=**5** clusters ...".

**Comment by ronaldpan** [comment]
![image](https://user-images.githubusercontent.com/13417382/129292293-88b50555-a5fb-4570-9297-234107171e17.png)

**Comment by ronaldpan** [comment]
![image](https://user-images.githubusercontent.com/13417382/129293982-0690922e-a71e-4440-b9f1-cfe548bc6899.png)

**Comment by murphyk** [comment]
fixed, thanks
