### ISSUE TITLE
Figure 1.7 mismatch between images, captions, and section text

### ISSUE THREAD

**Issue by pwroberts** [probml/pml-book#16]
Edition: Dec 31, 2020
Print pages: 9-10
PDF pages: 39-40

§1.2.2.2 says:

> In Fig. 1.7(b), we see that using D = 2 results in a much better fit.

However, the Fig. 1.7(b) image is a polynomial of degree 14, or at least that's what the title above it says. Assuming the figure images are arranged as intended, I think the section text meant to refer to 1.7(a), which is of degree 2, and is not currently referenced by the text.

Also, the caption under Fig. 1.7 reads, in part:

> (a-b) Polynomial of degrees 1 and 14"

The polynomial in 1.7(a) is of degree 2 (and is labeled as such above the graph). I assume the caption should instead read:

>(a-b) Polynomial of degrees ~1~ 2 and 14

**Comment by murphyk** [comment]
fixed
