### ISSUE TITLE
Feature request: Causal Effect Inference

### ISSUE THREAD

**Issue by JeanKaddour** [probml/pml-book#161]
Not an issue; just a topic suggestion for Book 2:

I think adding a section on causal effect inference/treatment effect estimation could be very interesting for readers. 

For the sake of simplicity, the section could just focus on the potential outcomes formalism.

See, for example, Chapter 2 and Chapter 7 in
https://www.bradyneal.com/Introduction_to_Causal_Inference-Dec17_2020-Neal.pdf

**Comment by murphyk** [comment]
Yes I like Brady's tutorial. @alexdamour is currently writing the causality chapter :)

**Comment by JeanKaddour** [comment]
Awesome! Looking forward to it :)

**Comment by murphyk** [comment]
@vveitch FYI
