### ISSUE TITLE
Suggestions for Chapter 4

### ISSUE THREAD

**Issue by stvhuang** [probml/pml-book#166]
1. P.116
In Figure 4.3, __Exponentially-weighted moving average__'s acronym is __EMA__, however, in the line below Equation 4.88, is __EWMA__. Consider using a consistent acronym.

2. P.134, Figure 4.14
Titles for Figure 4.14 (b), (c), and (d) are too small and can hardly notice them.

3. P.150, Equation 4.221
`F_{i,j}` should be `\mathbf{F}_{i,j}`.

**Comment by ronaldpan** [comment]
![image](https://user-images.githubusercontent.com/13417382/129439798-8cc418dc-a765-4ec8-b6e1-9532220bc87e.png)

**Comment by murphyk** [comment]
Are you saying the red underlined (1-beta) is incorrect for the contribution from y0?

**Comment by ronaldpan** [comment]
Yes. I think there is no (1-beta) before y0.

**Comment by ronaldpan** [comment]
In addition, if we let u0=y0， u1=βu0+(1-β)y0
this can make the average = constant if all yt=constant, t=0,1,2,...

**Comment by murphyk** [comment]
fixed, thanks
