### ISSUE TITLE
Minor typos in chap.19 of book1 (draft of August 3, 2021)

### ISSUE THREAD

**Issue by nak6** [probml/pml-book#168]
- p.630, sec.19.1.2: $\ell (f(\mathbf{x}), y)$ -> $\ell (f(\mathbf{x}), \mathbf{y})$

![screenshot](https://user-images.githubusercontent.com/61901044/129240009-f80e8f1d-1e70-4d14-8fb4-b52200129fe6.png)

---
- p.630, sec.19.2.4.1: semi-supervised -> self-supervised

![screenshot](https://user-images.githubusercontent.com/61901044/129239287-275ca643-01d8-4350-a30f-fdb594a10139.png)

**Comment by murphyk** [comment]
fixed, thanks
