### ISSUE TITLE
Typos in Chapter 7

### ISSUE THREAD

**Issue by ronaldpan** [probml/pml-book#171]
![image](https://user-images.githubusercontent.com/13417382/129432452-b7aa95da-42c4-4cf9-b446-861c4bf878f7.png)

**Comment by ronaldpan** [comment]
![image](https://user-images.githubusercontent.com/13417382/129433329-9b27e5b2-062c-4221-b5e3-0cf8d96db3f4.png)

**Comment by ronaldpan** [comment]
In Equation (7.51), it should state that the eigenvalues are of A^TA of AA^T.

**Comment by murphyk** [comment]
fixed
