### ISSUE TITLE
Typos in Chapter 7

### ISSUE THREAD

**Issue by ronaldpan** [probml/pml-book#172]
According to (7.249), this should be 
![image](https://user-images.githubusercontent.com/13417382/129479581-5b9e9b49-56c3-4a5e-b26f-a8e320488ca5.png)

**Comment by stvhuang** [comment]
P.237, Section 7.2.4.1

data vectors?

> <img width="1064" alt="Screen Shot 2021-08-16 at 12 29 28 AM" src="https://user-images.githubusercontent.com/15218222/129485475-095edf03-c566-457c-a7d7-230cf30affce.png">

**Comment by murphyk** [comment]
fixed, thanks
