### ISSUE TITLE
typos in Chapter 8

### ISSUE THREAD

**Issue by ronaldpan** [probml/pml-book#175]
![image](https://user-images.githubusercontent.com/13417382/129646464-fefc0046-e34f-44f0-bf6f-187bdc101b15.png)

**Comment by ronaldpan** [comment]
![image](https://user-images.githubusercontent.com/13417382/129646810-ad2aa7b1-ac71-4242-87d2-dd478013a8b8.png)

**Comment by ronaldpan** [comment]
Figure 8.22(b) is not referred in the text.

**Comment by ronaldpan** [comment]
![image](https://user-images.githubusercontent.com/13417382/129650724-abcc946a-2e51-4372-b04c-55f0a9dc9456.png)

**Comment by ronaldpan** [comment]
![image](https://user-images.githubusercontent.com/13417382/129656775-4ce8d309-b590-433b-aa7a-b978a5b29b7c.png)

**Comment by murphyk** [comment]
I think you are reading a very old version. The latest is August 15th, 2021...

**Comment by stvhuang** [comment]
The draft downloaded from [probml.github.io/pml-book/book1.html](https://probml.github.io/pml-book/book1.html) is still version __August 3, 2021__.
