### ISSUE TITLE
Equation (1.1)

### ISSUE THREAD

**Issue by ronaldpan** [probml/pml-book#176]
In Equation (1.1), what is the meaning of the semicolon ';' between x and θ?  Is there any difference between f(x;θ) and  f(x,θ)?

**Comment by murphyk** [comment]
the informal convention is that f(x; theta) suggests that theta is "fixed" and x as variable; but in reality theta is also changed during an outer loop optimization procedure, so it's a rather arbitrary difference from f(x, theta).
