### ISSUE TITLE
typos in Section 1.2 and Section 1.3

### ISSUE THREAD

**Issue by partev** [probml/pml-book#189]
![Screenshot 2021-08-22 13 48 47](https://user-images.githubusercontent.com/23830955/130364946-00f45342-e50b-444b-a46c-f02c0a48c8e5.png)
![Screenshot 2021-08-22 13 47 26](https://user-images.githubusercontent.com/23830955/130364950-d0b72692-6870-405a-ab59-dae9a9f064a9.png)

endogeneous -> endogenous
exogeneous -> exogenous

**Comment by murphyk** [comment]
fixed, thanks
