### ISSUE TITLE
Should attribute Kant quote to his actual work (maybe)

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#19]
On page 7, last paragraph, there is a quote from Kant.  It would be better to also mention which work it came from.  It seems that various sources (articles on Poker) claim that this quote is from:

_Critique of Pure Reason_

But it doesn't appear to be here:  https://www.gutenberg.org/files/4280/4280-h/4280-h.htm

So, I don't know where it really comes from or if it is indeed something that Kant said.  I've searched these works (from their online PDFs) and couldn't find it:

- Critique of Pure Reason
- Critique of Practical Reason
- Metaphysical Foundations of Natural Science
- Critique of Judgement

From December 31, 2020 edition.

**Comment by murphyk** [comment]
Good point. I rewrote this as 

\begin{quotation}
  [We must avoid] false confidence bred from an ignorance of the probabilistic nature of the world,
  from a desire to see black and white where we should rightly see gray.
  --- Immanuel Kant, as paraphrased by Maria Konnikova \citep{Konnikova2020}.
\end{quotation}
