### ISSUE TITLE
PML1: Typo in 13.2.1 The XOR problem

### ISSUE THREAD

**Issue by AndreaPi** [probml/pml-book#192]
Footnote 1:
>  (There are some exceptions, such as [Tol+21], where unstructured models can learn to perform well on image and text data, but such models need massive datasets to overcome their lack of inductive bias .

The closing parenthesis is missing.

PS amazing book, keep up the good work. This will become a classic, like the first edition did.

**Comment by murphyk** [comment]
fixed, and thanks for the praise :)
