### ISSUE TITLE
4.6.2.5 Example

### ISSUE THREAD

**Issue by partev** [probml/pml-book#200]
![image](https://user-images.githubusercontent.com/23830955/131239879-5719636f-bc17-4b9d-b832-8b1e16637fc7.png)

this text says alpha=2 and beta=2 implies that we saw 2 heads and two tails.
but according to formula:
![image](https://user-images.githubusercontent.com/23830955/131239900-ceee1d47-2a3b-4dbe-bad5-8c34da756498.png)
N_1 -> N_1 + alpha -1
in other words N_1 increases by 1 (alpha-1) not 2. So it is like seeing 1 head not 2.
Also when you have uninformed prior (alpha=1, beta=1) then it is like seeing 0 (alpha-1) heads and 0 tails before we see any data.. So I think the language should be updated.

**Comment by pglpm** [comment]
The text makes sense. It becomes clearer if you read for example the full explanation given in [Jaynes 2003](https://archive.org/details/XQUHIUXHIQUHIQXUIHX2), §12.4.3 (also [in this paper](https://bayes.wustl.edu/etj/articles/prior.pdf), around page 20), which in turn goes back to Jeffreys. It is very illuminating. Maybe the text could reference that.

The main point is that you should not consider the "-1" in the exponent. Imagine for example the beta written as
∝ [θ^α (1-θ)^β]/[θ (1-θ)]
Then the posterior is
∝ [θ^(N_0 + α) (1-θ)^(N_1 + β)]/[θ (1-θ)]
and from this point of view only α and β have been added. Indeed the presence of the "-1", that is the term 1/[θ (1-θ)], _could_ be motivated on information-geometric grounds as a sort of "base measure".

Intuitively speaking, the case α=β=0 means that no head or tails have been observed, so we don't even know if they are possible at all, and the beta distribution indeed diverges. Quoting Jaynes, "we can now interpret the Bayes-Laplace prior [α=β=1] as describing not a state of complete ignorance, but the state of knowledge in which we have observed one success and one failure. It thus appears that the Bayes-Laplace choice will be the appropriate prior if the prior information assures us that it is physically possible for the experiment to yield either a success or a failure, while the distribution for complete ignorance [α=β=0] describes a ‘pre-prior’ state of knowledge in which we are not even sure of that".

**Comment by partev** [comment]
thanks for the explanation @pglpm
