### ISSUE TITLE
Give a nod to Gauss in 1.2.2.1

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#21]
It can be argued that Gauss was the first person to do Machine Learning, since he developed Least Squares to predict astroid orbit:

https://en.wikipedia.org/wiki/Least_squares#The_method

I think it would be nice to add a historical foot note to this achievement.

It may be useful to mention that LS has the advantage of having a closed form solution (because quadratic is differentiable), where as L1 does not, which is why LS been held in favor for so long despite having trouble with outliers.

**Comment by murphyk** [comment]
I discuss all that in ch 11. (See also a nod to Gauss in 3.3.4 :)
