### ISSUE TITLE
Some Links from Chapter 1 Supplementary Material are broken

### ISSUE THREAD

**Issue by rohit901** [probml/pml-book#211]
Hi, 
I'm not able to access majority of the links from [Supplementary Material Chapter 1](https://github.com/probml/pml-book/blob/main/pml1/supplements/chap1.md).
I'm getting this error of "Notebook not found" when I try to access the first two links and even the material on "Other JAX tutorials".

**Comment by murphyk** [comment]
should be fixed now, please try again
