### ISSUE TITLE
Add other problem with labeling is inaccurate labeling

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#23]
page 11, section 1.3, 3rd paragraph, the text says:

"need to collect large labeled datasets for training, which can often be time consuming and expensive". 

From my experience the third under appreciated factor is the **accuracy** of labels.  This is especially true if managers are cutting corners by rushing the labeling and/or using cheap and inexperienced labor.  The labeling inaccuracy is often not easily estimated.  It is too easily to be blind-sided by label inaccuracy and end up with a poor model without realizing it until it's too late.

This problem can be magnified if some classes are vastly under represented.

**Comment by murphyk** [comment]
Ack. One reason labels are "inaccurate" is that class definitins are often fuzzy and not clear-cut.
See start of sec 1.3:

"Unsupervised learning also avoids the need to learn how to partition the world into often arbitrary categories. For example, consider the task of labeling when an action, such as “drinking” or “sipping”, occurs in a video. Is it when the person picks up the glass, or when the glass first touches the mouth, or when the liquid pours out? What if they pour out some liquid, then pause, then pour again — is that two actions or one? Humans will often disagree on such issues [Idr+17], which means the task is not well defined"
