### ISSUE TITLE
In 1.3, (unsupervised) doesn't discuss the problem of guessing how many clusters there are 

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#24]
In section 1.3, pp 11-13, does not discuss the problem of guessing how many clusters there. 

"then we might want to split the top right into (at least) two subclusters."  (p 12, section 1.3.1).

This is (obviously) a hard problem.  Maybe it's mentioned somewhere else in the book (so there should be a reference to that), but I haven't finished reading this very fine book yet!

12/30/2020 version.

**Comment by murphyk** [comment]
Added ref to 21.3.7 where I discuss this.
