### ISSUE TITLE
Possible errors and suggestions. Version Aug, 27, 2021. Chapter 2, 3, 6, 8, 18

### ISSUE THREAD

**Issue by Rajon010** [probml/pml-book#246]
I try to avoid listing errors which have been reported in other issues, but some duplicates may still exist.

1. P.599. Text between (18.5) and (18.6). "Alternatively, we could allow for a multi-way split, with <del>K<sub>k</sub></del> branches, as in Figure 18.2."
-> K<sub>j</sub>.

2. P.604. "There are 57 quantitative (real-valued) <del>predictors</del>, as follows"
 -> features

3. P.610. "By performing a Newton <del>upate</del> on this objective"
-> update

4. P.612. A period is missing just before section 18.5.5.1.

5. P.614. I understand what the author means but if the gain is defined as (18.56), it may be more mathematically correct to say "it is not worth splitting a node if the gain is less than **_zero_**"
![0](https://user-images.githubusercontent.com/11660172/140646251-e7582c62-ea92-4a8b-a197-d2e80e0d1d3f.jpg)

6. P.271. It may be a little strange to say "see section 8.1.3" because we are in section 8.1.3 now, and the desired definitions follow immediately.
![0](https://user-images.githubusercontent.com/11660172/140646778-f4443676-acdc-4436-bba1-d51efafaf113.jpg)

7. P.297.
![0](https://user-images.githubusercontent.com/11660172/140647170-771d3b9e-c6c5-46d6-986d-d224d612eb55.jpg)

8. P.309. I think this should be p<sup>*</sup>(z<sub>n</sub> = k | y<sub>n</sub>, &theta;<sup>(t)</sup>). Equation (21.23) seems to justify this modification.
![0](https://user-images.githubusercontent.com/11660172/140647555-4e34b23e-81f4-4bf7-89b5-001b489ab842.jpg)
![0](https://user-images.githubusercontent.com/11660172/140647833-c99ccb25-2077-4e23-a80b-6a92178d3bb1.jpg)

9. P.41. "They were computed using simulated annealing a derivative free optimization method ..." Missing a comma.
-> ... simulated annealing, a derivative ...
10. P.50. Missing "+b".
![0](https://user-images.githubusercontent.com/11660172/140648252-c12c3661-da02-4112-9f31-62b6f129960d.jpg)
11. P.55. I think the author means the Gaussian cdf rather than the error function, but a reader may be confused. Indeed, figure 2.2a is the Gaussian cdf, with cdf(0)=0.5 as opposed to erf(0)=0.
![0](https://user-images.githubusercontent.com/11660172/140648378-d7684402-7cb0-4961-8363-7014e699990e.jpg)
![0](https://user-images.githubusercontent.com/11660172/140648615-310485b6-38a7-43e0-9ab6-3627d2793c13.jpg)

12. P.94. After checking sections involving Mixture Models, EM Algorithm, and Clustering Using Mixture Models, I think the three probability functions should be conditioned on &theta; (in addition to other conditions which already exist).
![0](https://user-images.githubusercontent.com/11660172/140649206-d488a15c-6491-44d7-a5ae-14ac4724520e.jpg)

13. In section 3.5, I suggest explicitly writing down the definition of &theta;, &theta; = {&pi;<sub>1</sub>, ..., &pi;<sub>k</sub>, &theta;<sub>1</sub>, ..., &theta;<sub>k</sub>}. And in section 3.5.1, &theta;<sub>k</sub> = {&mu;<sub>k</sub>, &Sigma;<sub>k</sub>}. I am quite sure that &pi; &in; &theta; because section 21.4.1 states it, but I am not sure whether &pi;<sub>k</sub> &in; &theta;<sub>k</sub> or not.
![0](https://user-images.githubusercontent.com/11660172/140650043-def76bd8-9bbc-44b6-8462-997fd31a5315.jpg)

What a great book. I can't wait to read the sequel.

**Comment by Rajon010** [comment]
14. Page 200, figure 6.2 b. The text says that the y value of this figure is something involving entropy, but it looks as if it is relative frequency.

**Comment by murphyk** [comment]
thank you for this useful feedback, I have fixed these errors, the corrections will appear in the next online edition that I will post shortly.
