### ISSUE TITLE
Small error on p. 259

### ISSUE THREAD

**Issue by pat-alt** [probml/pml-book#250]
I've been studying the draft of book 1 and love it - thanks a lot for open-sourcing it!

Unless I'm missing something, I believe there is small error on p. 259. You state:

> To ensure a unique solution, we use a (spherical) Gaussian prior centered at the origin, N (w|0, σ^2I). The value of σ^2 controls the strength of the prior. If we set σ^2 = ∞, we force the MAP estimate to be w = 0; this will result in maximally uncertain predictions, since all points x will produce a predictive distribution of the form p(y = 1|x) = 0.5. If we set σ^2 = 0, the MAP estimate becomes the MLE, resulting in minimally uncertain predictions.

In my understanding, the higher the uncertainty σ around the prior, the lower its impact on the posterior: prior beliefs are not precise, so easily discarded in the face of evidence/data. In fact, you make precisely this argument on p. 137:

> If the prior is weak relative to the signal strength (􏰰λ is small relative to κ), we put more weight on the empirical mean. If the prior is strong relative to the signal strength (􏰰λ is large relative to κ), we put more weight on the prior.

Applied to the context of p. 259 we have λ=1/σ^2, so for σ^2 = ∞ our prior is infinitely weak and hence the MAP estimate will be fully dominated by the data (MLE). Conversely, for σ^2 = 0 the prior fully dominates the data and hence the posterior will equal the prior, i.e. N (w|0, σ^2I) and hence p(y = 1|x) = 0.5 everywhere. I've also tested this empirically using Python's `bayes_logistic` library and my own implementation in Julia (see [here](https://www.paltmeyer.com/post/bayesian-logistic-regression/)). 

Once again, thanks a lot, really love this book! And my apologies if I'm the one who's mixing things up here.

**Comment by murphyk** [comment]
Yes, you are right (and I assume you mean p359 :)
Fixed.
