### ISSUE TITLE
Quadratic programming Lasso formulation

### ISSUE THREAD

**Issue by dogandzic** [probml/pml-book#252]
You state in 8.5.4.2: "There are several applications of quadratic programming in ML. In Section 11.4, we show how to use
it for sparse linear regression."
Then I looked at 11.4.

I was expecting some reference to GPSR paper, [FNW07] or some formulation like the one in 11.6.1.1.
I.e., showing how to reformulate lasso as a quadratic-programming problem which can then be fed into generic cvx or cvxpy packages. I am guessing that this is not efficient computationally, but would fit your statement "show how to use
it for sparse linear regression."

**Comment by dogandzic** [comment]
I can see it in 11.4.9.2. Anyway, was not easy to find with so many subsections. Perhaps it would help to guide a bit more precisely.

**Comment by murphyk** [comment]
Yes I should cite eqn 11.103 for how to formulate Lasso as a QP. Fixed.
