### ISSUE TITLE
1.5.4.3 - Word Embeddings (needs rewording)

### ISSUE THREAD

**Issue by Alxmrphi** [probml/pml-book#255]
Original:

_Although the TF-IDF transformation improves the vector representation of words by placing more
weight on “informative” words and less on “uninformative” words, it does not overcome the fundamental
issue that semantically similar words, such as “man” and “woman”, may be further apart (in vector
space) than semantically dissimilar words, such as “man” and “banana”._

Problem:

I believe it should state that word vectors for _man_ and _woman_ should be **closer together** (not further apart) than semantically dissimilar items (and that this is the benefit of using vector space models instead of one-hot dictionary-level vectors representing lexical units).

**Comment by wilfreddesert** [comment]
I believe everything is correct in this case. The fundamental issue is that semantically similar words may be further apart in vector space. Exactly what the passage says :)

**Comment by Alxmrphi** [comment]
Oh, right. It doesn't make sense to me, then. What is the point of having the word "banana" closer to "man" in vector space, than "woman". It goes against the idea that semantically similar words tend to cluster together in (well-behaved) vector space language models.

**Comment by wilfreddesert** [comment]
_the fundamental
issue that semantically similar words, such as “man” and “woman”, may be further apart (in vector
space) than semantically dissimilar words, such as “man” and “banana”._

In the perfect scenario, "man" and "woman" are closer to each other than "man" and "banana" as two semantically similar words. 

There might be a problem though with TF-IDF (in this example). It doesn't take the semantic similarity into account and this is why the opposite may become true: the distance between "man" and "banana" is smaller than between "man" and "woman" can be smaller, which doesn't make sense semantically.

**Comment by murphyk** [comment]
I reworded it thus. HTH.
```
Although the TF-IDF transformation improves  on raw count vectors
by placing more weight on ``informative'' words
and less on ``uninformative'' words,
it does not solve the fundamental problem with the one-hot encoding
(from which count vectors are derived),
which is that
that semantically similar words, such as ``man'' and ``woman'',
may be not be any closer (in vector space)
than semantically dissimilar words, 
such as ``man'' and ``banana''.
```

The point is that TF-IDF doesn't usually help much compared to learned word embeddings.
However in some cases it can work better (eg see https://simpragma.com/blog/performance-analysis-of-text-similarity/).
