### ISSUE TITLE
Typo in "Bayes rule for Gaussians"

### ISSUE THREAD

**Issue by andreimargeloiu** [probml/pml-book#256]
In the third line in equation 3.37 it should be the inverse of the posterior matrix.

Instead of \Sigma_{z|y} is should be \Sigma_{z|y}^{-1}

![E49F8E3B-6508-4F01-8198-2B9ED16E623F](https://user-images.githubusercontent.com/18227298/145675716-d79b7aa1-f663-4b8c-81b0-9db87cb878df.png)

**Comment by murphyk** [comment]
No it is correct as it is. The derivation follows from eqn 3.28.
