### ISSUE TITLE
Typo in chapter 19, Book1

### ISSUE THREAD

**Issue by houtan-ghaffari** [probml/pml-book#257]
Hello,

1) I think the negative sign in the first term of the equation (19.10) should be removed(?), page 631.

2) Page 634, Figure 19.8 never referenced in the text. Also, I think the description for Figure 19.8 (a) should be "Decision boundary we might learn given only **labeled** data", not "unlabeled".

3) Page 636, equation (19.17), I think the second "P(.)" in front of the logarithm should also include a subscript theta, "P_{\theta}". It was clear from the text, but confusing by the equation alone whether the two probability are coming from the model (If I am getting it right).

4) Page 636, last paragraph, second line, "abru**p**tly" written as "abru**b**tly".

5) Page 638, equations (19.24) and (19.25) both have an extra closing bracket "]" at the end.

6) Page 639, after the equation (19.26), the fifth line, regarding the inline equation for normalizing the rows of "Y", shouldn't the indices of "Y" in the summation be "Y_{i,k}" instead of "Y_{k,c}"?

Thanks

**Comment by murphyk** [comment]
Fixed, thanks!
