### ISSUE TITLE
Missing minus sign in equation 16.13

### ISSUE THREAD

**Issue by soenkesuedbeck** [probml/pml-book#258]
![wrong_sign_in_equation_16_14](https://user-images.githubusercontent.com/64035904/147934284-3ee7cedd-2ab3-4fb1-adc2-177416f2a11b.png)

I believe there is a small typo in equation 16.13. There should be a minus sign in front of the log as in equation 6 of the [original paper](https://papers.nips.cc/paper/2016/file/6b180037abbebea991d8b1232f8a8ca9-Paper.pdf).

**Comment by murphyk** [comment]
Thanks, fixed!
