### ISSUE TITLE
chapter 1 notation of decision rule 

### ISSUE THREAD

**Issue by algotrex** [probml/pml-book#259]
In page 8, equation 1.14:

I want to make the suggestion that the notation of having the function f(x; \theta) in the conditional is slightly confusing, it would be nicer to have it stated as done in equation 1.9 to be consistent.

So RHS of 1.14 should read: -log p (y | x; \theta). 

Not biggest issue in the world :) and it's a great book.

**Comment by murphyk** [comment]
I see your point, but I will keep it as is.
