### ISSUE TITLE
AI Ethics and inadequate training sets

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#26]
AI Ethics is mentioned in section 1.5.

One thing that is not mentioned, is the danger of (unconsciously) picking a biased training set (which is not mentioned in Section 1.2).

That is exemplified by Google's image recognition that misidentified pictures of Blacks as apes. 

See:

https://www.theguardian.com/technology/2018/jan/12/google-racism-ban-gorilla-black-people

**Comment by murphyk** [comment]
I cite this paper that covers these and other topics

https://ml-retrospectives.github.io/neurips2020/camera_ready/19.pdf
 “Data and its (dis)contents: A survey of dataset develop- ment and use in machine learning research”.
