### ISSUE TITLE
Mistaken numerical answer on page 201

### ISSUE THREAD

**Issue by NightMachinary** [probml/pml-book#260]
![image](https://user-images.githubusercontent.com/36224762/149141650-92e16657-113b-4719-9fff-384045f807a9.png)

`100*(2e-4/(1+1e-4))` equals `0.02%`, not `0.2%`.

---

This section has me confused on several fronts:
1. Why is beta taken to power 2 here?
![image](https://user-images.githubusercontent.com/36224762/149142021-6a83b774-0c07-4dc1-9606-9c1aeb7cdf94.png)

2. Is there a mathematical justification for using the harmonic mean here? E.g., we can easily prove that the harmonic mean is correct for taking the average of speeds in physics. If not, I think it bears saying it explicitly that we are just using this mean "empirically."

**Comment by murphyk** [comment]
I changed 0.2% to 0.02%.

The convention of using beta^2 is indeed odd, but I copied it from https://en.wikipedia.org/wiki/F-score#F%CE%B2. I have added a citation to this source.

 As for why people use harmonic mean, it is just heuristic, AFAIK.
