### ISSUE TITLE
Book 1, section 2.2.6 (Anscombe’s quartet statistics)

### ISSUE THREAD

**Issue by mtreviso** [probml/pml-book#264]
For the Anscombe’s quartet dataset, the book reports:
**V[x] = 11**
**V[y] = 4.125**

But  according to the formula presented in the book `V[x] = E[(x-mu)^2]`, we get:
**V[x] = 10**
**V[y] = 3.75**

The difference between the reported numbers and the "correct" ones is probably due to the difference between computing variances using pandas' `.var()` and numpy `.var()`. Pandas uses `N-1` in the denominator (unbiased estimator),  numpy does not. See more here: https://stackoverflow.com/a/24984205/4181815.

Code to reproduce:
```python
import seaborn as sns
df = sns.load_dataset('anscombe')
for d in ['I', 'II', 'III', 'IV']:
    y = df[df['dataset'] == d]['y'].to_numpy()
    print('{:.2f}'.format(((y - y.mean())**2).mean()))
    print('{:.2f}'.format(y.var()))
    print('{:.2f}\n'.format(y.var(ddof=1)))
```

**Comment by murphyk** [comment]
Nice catch! (It turns out that fig 2.5 also pointed to the wrong script, it should be https://github.com/probml/pyprobml/blob/master/scripts/anscombes_quartet.py.) Both issues are now fixed.
