### ISSUE TITLE
Book 1, Chapter 8 comments

### ISSUE THREAD

**Issue by vihari** [probml/pml-book#265]
Thanks for releasing your book publicly.
Some comments from Chapter 8 on Optimization of Book 1. 
The page numbers below refer to the page number marked on the page. Linked PDF contains issues marked in red on each page. 

1. p294; first para, f is referenced without introducing. I think f is mistaken for L.
2. p294; Last para before (8.99) contains sentence of the form: "Since both <vector1> and <vector2> are orthogonal to constraint surface, they must be parallel..."--the statement need not be true when the constraint surface does not span all dimensions. Am I missing something?
3. p295; first para, last bit: \grad f(\theta^*)=0, f again (see point 1 above), possibly meant L.
4. A loose comment: I think Sec 8.5.1, 8.5.2 can be organized better. I find 8.5.2's motivation more natural and would have preferred 8.5.1 started with that. 
5. p296; in eq. 8.111, taking from 8.108, should have been '+' \mu g
6. p296; between eq 8.112, 8.113, missing 'that' before 'all'.
7. p301; eq 8.136, should have been \theta_d instead of x_d.
8. p302; eq 8.142, \theta_0 should replace z.

The annotated PDF can be found here: https://drive.google.com/file/d/1GgKBkyG73nqLZ_m2xaOt9ASbmlT-iAEU/view?usp=sharing

**Comment by murphyk** [comment]
Thanks. I have fixed these issues. (Note that some were already fixed in the Nov 8 version, which matches the first print version more closely that the May 21 version you are reading. I will upload a newer version on Feb 7th, with the latest round of small fixes. But I am not making major rewrites, eg rewording sec 8.5.1.)
