### ISSUE TITLE
Error on page 260, inverse term undefined

### ISSUE THREAD

**Issue by thobanster** [probml/pml-book#266]
Near the end of section 7.7.2 on page 260 it says:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/65133891/152687448-66c25fbc-3e3a-4fef-8177-007d66271315.png">
This doesn't make sense in the context of this section because A is a wide matrix such that m < n, so the term inside the inverse is not full rank, so therefore the inverse (and therefore the left pseudoinverse) is not defined. 

More generally, I also think the reasoning behind equation 7.232 is left unexplained (i.e. why the term that looks more like the left pseudoinverse ends up converging to the right pseudoinverse, or the minimum norm solution). This is because you can refactor the term on the left, but the book doesn't show that.

**Comment by murphyk** [comment]
yes, I think you are right -  I will remove the incorrect content (which unfortunately will change the equation numbers for the rest of this chapter....)

**Comment by murphyk** [comment]
yes, but 7.232 repeats the result that was already stated inline after 7.228. And I find what I wrote confusing.
I have instead figured out how to "artificially" increment the equation number at the end of this section,
so remaining numbers will be the same. So the new version will look like this (modulo chap 1 -> chap 7):

<img width="658" alt="Screen Shot 2022-02-08 at 6 15 16 PM" src="https://user-images.githubusercontent.com/4632336/153109048-75478335-d404-4870-9105-34ce445f65c8.png">
