### ISSUE TITLE
Error in book 1, page 66

### ISSUE THREAD

**Issue by a-fakhri** [probml/pml-book#267]
The matrix A and figure 2.20b are not consistent. Either the positions of elements b and c should be changed in the matrix or the transformed points' labels in the aforementioned figure should be changed. For instance, (a, b) should be changed to (a, c), since that is the correct transformation of a vector (1, 0) by matrix A.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/65111198/152844190-07994c16-072c-4cf7-88c7-a63729adf1d8.png">

**Comment by murphyk** [comment]
you are right! fixed.
