### ISSUE TITLE
Chapter Recommendation: AI, ML, and Model Ethics

### ISSUE THREAD

**Issue by StevenBBryant** [probml/pml-book#268]
Book 2 Recommendation

I think it would be great to include a chapter associated with the ethical considerations of model development. I don't think this needs to be prescriptive in how to resolve issues. Rather, I would envision a chapter that recognizes the importance to "think" about the model and solution prior to deployment.  There have been sufficient examples in the press of LARGE companies with LARGE AI shops what make the media when they get it wrong. If this happens with large companies with teams that should be thinking about things like this, the risks are magnified in smaller organizations if they do not have people thinking about some of the risks and how they might be mediated.

Thank you in advance for your consideration of such a chapter.

**Comment by murphyk** [comment]
In book 2, I have a (guest) chapter on interpretability, which touches on some related issues, but I do not have time or space to add more content.... (draft of vol 2 coming out real soon!)
