### ISSUE TITLE
Bayesian stuff

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#27]
A few points about Bayes stuff section 2.2 and 2.2.1, pp 21-23

1. I think you should mention the Frequentist approach to probability.  One aspect is that Bayes will hazard an estimate to an event that has no prior examples, where a Frequentist wouldn't dare.  This would be something like election results.

2. Sometimes, the terms in the Bayes formulas are estimates, so there can be a lot of uncertainty in the answer.  E.g. how do you get an accurate value for the P(H=1)?  This can be hard.

3. It would be nice to show the numeric values substituted in for the equations 2.6 and 2.9.

4.  The thing that trips up people about Bayes is differences in prior probability can radically change the result.  A would be a good to recalculate the COVID example in 2.2.1 for different values of (PH=1).  For instance, early in the COVID pandemic, the P(H=1) might be 0.01 or 0.001.  Then the probably of FP of a test will become very large.  This unintuitive result catches a lot of people by surprise.  [added] I do see you show this in Exercise 2.1.

I calculate for p(H=1)=0.01 that the probability of infection drops to 26%.  If p(H=1)=0.001 (the disease is very rare), then probability of infection drops to 3%.

This is true even though the test is highly accurate.

**Comment by murphyk** [comment]
> A few points about Bayes stuff section 2.2 and 2.2.1, pp 21-23
> 
> 1. I think you should mention the Frequentist approach to probability. 

See appendx D


> One aspect is that Bayes will hazard an estimate to an event that has no prior examples, where a Frequentist wouldn't dare.  This would be something like election results.
> 2. Sometimes, the terms in the Bayes formulas are estimates, so there can be a lot of uncertainty in the answer.  E.g. how do you get an accurate value for the P(H=1)?  This can be hard.

ack

> 3. It would be nice to show the numeric values substituted in for the equations 2.6 and 2.9.

done

> 4. The thing that trips up people about Bayes is differences in prior probability can radically change the result.  A would be a good to recalculate the COVID example in 2.2.1 for different values of (PH=1).  For instance, early in the COVID pandemic, the P(H=1) might be 0.01 or 0.001.  Then the probably of FP of a test will become very large.  This unintuitive result catches a lot of people by surprise.  [added] I do see you show this in Exercise 2.1.

Yes, added ref to that exercise

> 
> I calculate for p(H=1)=0.01 that the probability of infection drops to 26%. If p(H=1)=0.001 (the disease is very rare), then probability of infection drops to 3%.
> 
> This is true even though the test is highly accurate.
