### ISSUE TITLE
Book 1, Chapter 2, Section 2.2.4 - Inconsistency in notation?

### ISSUE THREAD

**Issue by h-vijayakumaran** [probml/pml-book#270]
While reading the book, I felt that there is some inconsistency in the way the the equations in section 2.2.4 are represented. 
For example, in my opinion, the equation 2.21 (see below):
X ⊥ Y ⇐⇒ p(X, Y) = p(X)p(Y)
should take the form:
X ⊥ Y ⇐⇒ p(x, y ) = p(x)p(y) 
to be consistent with the previous and following sections.
Same goes with the equations 2.22, and 2.23. This is not a big deal, but I feel it would help reinforce a notation system in the mind of the reader.

**Comment by amfys2001** [comment]
First, it is important to define what the notation P(X, Y) means --- this is not done in the text. Surely, I can infer that. However, an author should not expect this from the reader. I agree with you, some care is needed with respect to definitions and notations. This would certainly increase the overall book quality.

**Comment by murphyk** [comment]
It's true I have been a little inconsistent with P(X) vs p(x). It's too much work to fix this now...
