### ISSUE TITLE
Chap 16 Deep Neural Neworks

### ISSUE THREAD

**Issue by simonjdprince** [probml/pml-book#273]
Feb 17 2022 build

P588 L45  visualiziob--> visualization
P589 Eq 16.4  Might be worth mentioning that this is not typical def of convolution (no minus signs)
P595 L41  If $f$ and $f$ are affine --> If $f$ and $g$ are affine
P596 L45 \mathbf{h}_{1}^{*} is not defined anywhere
Figure 16.11 caption "square boxes --> dotted square boxes".  (there are a lot of square boxes in this figure!)
P600 L37  I don't understand why Q=V=K=X.  These matrices don't even usually have the same dimensionality.  Something I'm not getting here, but maybe not an error.
P601 L29 Similarly, I don't understand why Q=V=K=Y
P607 L28 "In the practice... abundant pattern"  Maybe rewrite this sentence?  
P612 L11 "load-bearding" --> load-bearing
P614 L17 "mdeo" --> mode
Throughout -- decide between "forward mode", "forward-mode" and "forwards mode"
Throughout -- figure out if you are going to punctuate equations as 16.54 or not as 16.4

Overall, I would suggest separating into two chapters. The autodiff stuff is at a much finer level of detail relative to the building blocks themselves and it's rather jarring jumping from one to the other.  Also, autodiff doesn't really fall under the category of "deep learning"

**Comment by murphyk** [comment]
Thanks, Simon. I am moving your comments to https://github.com/probml/pml2-book/issues
