### ISSUE TITLE
Chap 21:  Generative models: an overview

### ISSUE THREAD

**Issue by simonjdprince** [probml/pml-book#275]
February 17th version

P767  Bayes' rule equation p(x)-->P(x|z)
P768  L35  It's not strictly true that factor analysis is aka PPCA.  More precisely, PPCA is a special case of factor analysis.
P770 L5 -LL --> NLL (to be consistent with previous page)
P774 L28 one can train classifier --> one can train a classifier
P775 L4&5   Chapter 24 --> (Chapter 24),  Chapter 22 --> (Chapter 22)

**Comment by murphyk** [comment]
Thanks Simon. I'm moving this to
https://github.com/probml/pml2-book/issues/2
