### ISSUE TITLE
Another reason why Bayes is relevant in the “big data era” and "deep learning era"

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#28]
In section 2.4.6, page 40

There is another reason as to why Bayes is still relevant.

I encountered this in my professional career:  if the amount of data is huge (and the features aren't very predictive), Bayes can beat other forms of ML because it's much quicker to calculate the probabilities during evaluation.  (This surprised me!)

This is also true for Bayes vs. Deep Learning which can be painfully slow, even with GPUs.

**Comment by murphyk** [comment]
ack
