### ISSUE TITLE
Typo N-pairs loss, page 550 (printed version)

### ISSUE THREAD

**Issue by djmarti** [probml/pml-book#281]
Page 550 (print in hardcopy book), N-pairs loss:

Equation 16.12, the minus sign on the right hand side seems wrong.

Equation 16.13, the numerator should involve the dot product of the embedding of the anchor and the embedding _of the positive example_, not of a negative example (the index _k_ appears as free index, which is not consistent with the left hand side of the equation). In short, the scalar product in the numerator be with

```math
... \hat{\boldsymbol{e}}_{\boldsymbol{\theta}} (\boldsymbol{x}_{j}^{+})
```
The minus sign in Eq. 16.13 is correct (but doesn't follow from Eq. 16.13).

Equation 16.14: if the sign in 16.12 is wrong, the minus sign in front of log should be removed.
Equation 16.15: likewise, the minus sign in front of max should be removed. 

Awesome book, by the way.

**Comment by murphyk** [comment]
Yes, you're right, many indices were messed up. I think I've fixed it now (will appear next time I update the online pdf):
<img width="677" alt="Screen Shot 2022-04-09 at 3 32 55 PM" src="https://user-images.githubusercontent.com/4632336/162593676-aa49400c-ea1e-4c94-aba6-77624aaea06d.png">
