### ISSUE TITLE
[Potential typos] pml2, section 5.1

### ISSUE THREAD

**Issue by VincentMeijer** [probml/pml-book#283]
This is an absolutely brilliant section which helped my understanding of the KL divergence: Thank you for making this draft available. I noticed some potential typos while reading. 

Page 184:
* Line 23: Should "its" be "it's" ?

Page 186: 
* Line 38: Should "its" be "it's" ?

Page 188:
* Line 14: "Henec" instead of "Hence"

Page 189:
* Line 28: Wouldn't "I.J. Good" read better than "IJ Good" ?

Page 193:
* Line 28: "pass" instead of "mass"

**Comment by murphyk** [comment]
fixed, thanks
