### ISSUE TITLE
Typo in 7.8.1

### ISSUE THREAD

**Issue by 0xasim** [probml/pml-book#288]
<img width="763" alt="Screen Shot 2022-03-07 at 11 04 01 PM" src="https://user-images.githubusercontent.com/37139450/157092586-fb301f92-3fbc-4024-97ab-e129cfceada4.png">
"We define its derivative at a point a"
shouldn't it be 
"We define its derivative at a point x"?

**Comment by murphyk** [comment]
fixed, thanks
