### ISSUE TITLE
Figure 21.2

### ISSUE THREAD

**Issue by dogandzic** [probml/pml-book#294]
The text describing the example in Figure 21.2 seems to assume city-block distance. But, the code used to generate this figure does not indicate that. I assume the default distance will be Euclidean. Anyway, probably the clustering yields the same result either way in this example. I am just curious if the code is actually running for Euclidean distance.

I guess the command should be 

linked = linkage(X, 'single',metric='cityblock')

for city-block distance.

**Comment by murphyk** [comment]
You are right. I fixed the error in https://github.com/probml/probml-notebooks/blob/main/notebooks/agglom_demo.ipynb. It turns out it does not affect the results.
