### ISSUE TITLE
Notation unclear in sections 8.4.6.1 & 8.4.6.2

### ISSUE THREAD

**Issue by iprada** [probml/pml-book#296]
Hi,

I read through the sections AdaGrad and RMSProp sections on chapter eight, and I suspect you use the letter **_d_** to indicate the per-parameter learning rate. However, what is **_d_** was unclear to me from the text. I think it will greatly improve readability if the role of  **_d_** is defined in the text.

best,

Iñigo

**Comment by murphyk** [comment]
I added the comment "where $d=1:D$ indexes the dimensions of the parameter vector,"
