### ISSUE TITLE
Book 2 (version 2022-04-01), Section 12.2.4, Page 498-500: Missing Listing reference 

### ISSUE THREAD

**Issue by nipunbatra** [probml/pml-book#300]
<img width="423" alt="Screenshot 2022-04-02 at 10 16 40 AM" src="https://user-images.githubusercontent.com/60985/161366740-9ac3e96a-e9c2-4d11-aea1-1268cf532bb8.png">

**Comment by murphyk** [comment]
fixed, thanks
