### ISSUE TITLE
Typo in chapter 15.2.8 Beam Search

### ISSUE THREAD

**Issue by giladfelsen** [probml/pml-book#301]
In paragraph three, in ch. 15.2.8 When the text references Figure 15.12a in reference to timestep it is written that the probabilities are [0.1, 0.4, 0.3, 0.3]. However, the probabilities in the Figure are [0.1, 0.4, 0.3, 0.2] which appear to be the correct values as they sum to 1.

**Comment by murphyk** [comment]
fixed, thanks
