### ISSUE TITLE
Book 2, Ch. 30, Pg. 175 - missing reference

### ISSUE THREAD

**Issue by a-fakhri** [probml/pml-book#305]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/65111198/162877466-3048f0a0-ab1c-49fa-ae12-2e2eaae07742.png">

**Comment by a-fakhri** [comment]
A few more instances of ?? on page 180:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/65111198/162877889-3ea649d9-739c-4507-89ed-b90818057ec4.png">

**Comment by a-fakhri** [comment]
I am starting to come across a lot of ?? in the second book. Are these placeholders or was there an issue with compiling the pdf?

**Comment by murphyk** [comment]
I haven't had time to fix broken cross references yet... (It's because I've been moving material in and out of the supplementary material, based on page count constraints, and my changing opinion about what I can afford to 'drop'.)
