### ISSUE TITLE
Typos in chap 16

### ISSUE THREAD

**Issue by yuanx749** [probml/pml-book#306]
p541, figure 16.1: tesselation -> tessellation
p545, line 6: succesful -> successful
p550, section 16.2.5.1: uniformative -> uninformative

p550, equation 16.12. It seems the brackets should be removed, or place the right bracket at the end before the big parenthesis, otherwise the parentheses in the `exp()` do not match. 

Thanks for these great books.

**Comment by murphyk** [comment]
fixed, thanks
