### ISSUE TITLE
XGBoost may support Categorical variables directly some day

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#31]
on page 575, it says: "XGBoost assumes the user has preprocessed them into one-hot vectors"

This may change by the time you go to print.  Categorical variables are being experimented with:

https://github.com/dmlc/xgboost/releases/tag/v1.3.0

> Experimental support for direct splits with categorical features
> Currently, XGBoost requires users to one-hot-encode categorical variables. This has adverse performance implications, as the creation of many dummy variables results into higher memory consumption and may require fitting deeper trees to achieve equivalent model accuracy.
> The 1.3.0 release of XGBoost contains an experimental support for direct handling of categorical variables in test nodes. Each test node will have the condition of form feature_value \in match_set, where the match_set on the right hand side contains one or more matching categories. The matching categories in match_set represent the condition for traversing to the right child node. Currently, XGBoost will only generate categorical splits with only a single matching category ("one-vs-rest split"). In a future release, we plan to remove this restriction and produce splits with multiple matching categories in match_set.
> The categorical split requires the use of JSON model serialization. The legacy binary serialization method cannot be used to save (persist) models with categorical splits.
> Note. This feature is currently highly experimental. Use it at your own risk. See the detailed list of limitations at #5949.

In addition, the user doesn't have to explicitly use one-hot encoding for XGBoost (at least with the H2O.ai version).  It gets converted behind the scenes:

https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/xgboost.html
https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/categorical_encoding.html

> categorical_encoding: Specify one of the following encoding schemes for handling categorical features:
> 
> auto or AUTO: Allow the algorithm to decide. In XGBoost, the algorithm will automatically perform one_hot_internal encoding. (default)
> 
> one_hot_internal or OneHotInternal: On the fly N+1 new cols for categorical features with N levels
> 
> one_hot_explicit or OneHotExplicit: N+1 new columns for categorical features with N levels
> 
> binary or Binary: No more than 32 columns per categorical feature
> 
> label_encoder or LabelEncoder: Convert every enum into the integer of its index (for example, level 0 -> 0, level 1 -> 1, etc.)
> 
> sort_by_response or SortByResponse: Reorders the levels by the mean response (for example, the level with lowest response -> 0, the level with second-lowest response -> 1, etc.). This is useful, for example, when you have more levels than nbins_cats, and where the top level splits now have a chance at separating the data with a split.
> 
> enum_limited or EnumLimited: Automatically reduce categorical levels to the most prevalent ones during training and only keep the T (10) most frequent levels, and then internally do one hot encoding in the case of XGBoost.

I haven't gotten through your book, so I'm not sure if you mention that one of the problems with one-hot encoding, is that it causes an explosion of features, which can cause an effective dilution of the data, in that the information that the one-hot encoded values are mutually exclusive but not "seen" by many (all?) algorithms.

**Comment by murphyk** [comment]
I tweaked the wording for xgboost.
Re problems with one-hot. I discuss this briefly in the context of word embeddings in 19.5

**Comment by gitclem** [comment]
I find that beginners in ML, often blithely do one-hot encoding without realizing the consequences.  Even worse, sometimes they do an arbitrary string to integer mapping (obviously bad.)

I don't know if you know about this post, but it's pretty interesting:

https://kiwidamien.github.io/are-you-getting-burned-by-one-hot-encoding.html

One thing that some people don't think about, is sometimes it's worth collapsing some of the categories that are somewhat similar in a categorical feature.

One thing that surprised me, is that with Tree-based algorithms, they tend to ignore features (such as one-hot encoded features) that are rare despite being very accurate.  (This is because the information gain is so small.)

These various effects become noticeable if you experiment with them, but most people don't.

I am a fan of CatBoost because of how it can deal with categorical features but on the downside, it's can be more expensive train.
