### ISSUE TITLE
p. 34 probability of taking a specific real value

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#310]
"By allowing the size of the intervals to shrink to zero, we can represent the probability of X taking on a specific real value, as we show below". 

I am not sure I follow the text here. For a pure continuous random variable the probability of taking on a specific real value is always zero. The set of all real numbers is uncountable and so is any finite piece of real axis. Am I missing something here?

**Comment by murphyk** [comment]
It's just meant as an intuition.
