### ISSUE TITLE
Section 2.8.5 The convolution theorem

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#311]
I think the proof of the theorem could be made simpler and more 'probabilistic' using the marginalization argument together with conditional. 

By the definition of the marginal of $y$ we have this: $p(y) = \int p(y, x_2) dx_2 =  \int p(y | x_2) p_2(x_2) dx_2$. Since $y = x_1 + x_2$, $p(y | x_2) = p_1(y-x_2)$, from which $p(y) = \int p_1(y-x_2) p_2(x_2) dx_2$ follows directly.

Obviously, no additional calculus rules are necessary here.

**Comment by murphyk** [comment]
Yes I like this, it mirrors the discrete case in 2.168. However I don't want to mess with the equation numbering in the printed book...
