### ISSUE TITLE
Jcobian J_f(x), page 432, before 13.23

### ISSUE THREAD

**Issue by reeteshmukul** [probml/pml-book#312]
![image](https://user-images.githubusercontent.com/8973127/163714577-16ee0008-1655-4513-a674-99b63326277f.png)

Why did we use the transpose of x in the denominator?

**Comment by murphyk** [comment]
It's explained here:
https://en.wikipedia.org/wiki/Matrix_calculus#:~:text=Layout%20conventions%5Bedit%5D
However I don't use this consistently, so will remove it.
