### ISSUE TITLE
Section 5.2.4, reference to LOO-CV is wrong

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#315]
The text implies that equations (5.52)-(5.55) link marginal likelihood and and the leave-one-out cross-validation. However, I believe that the equations are not describing the LOO-CV procedure at all. Instead, $y_n | y_{1:n-1}$ represents a variant of a sliding window CV (fit model on all previous samples and test on the next one). In contrast, a LOO-CV would have to have the conditioning on all samples in the training set except for the one whose probability is evaluated, for example like this: $y_n | y_{1:n-1,n+1:N}$ https://en.wikipedia.org/wiki/Cross-validation_(statistics)#Leave-one-out_cross-validation. However, with this conditioning the chain rule factorization in (5.52) would not hold anymore. Also, for the leave-one-out CV, the final remark about "A complex model will overfit the "early" examples ..." would not make much sense, as in LOO-CV for each sample left out we use all remaining training samples to estimate model parameters.

Was it really meant to prove the link between LOO-CV and marginal likelihood, or perhaps another CV scheme was in mind?

**Comment by murphyk** [comment]
I clarified that this an approximation. (Fong2018 makes it precise.)
