### ISSUE TITLE
Section 8.5.2, use of g

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#320]
In the previous part of the book, and especially throughout Section 8, g was used to denote gradient. In section 8.5.2 g is used to denote inequality constraint. This is confusing, especially when g is used in bold in equations (8.104) and (8.106). I think using another letter to denote inequality constraints could lead to less confusion.

**Comment by murphyk** [comment]
I followed Wikipedia's notation. It's impossible to not reuse symbols - you need to use context to disambiguate.

https://en.wikipedia.org/wiki/Karush%E2%80%93Kuhn%E2%80%93Tucker_conditions
