### ISSUE TITLE
Section 8.7.2.1, page 308, eq. (8.155)

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#321]
It seems to me that the notation is inconsistent between eq (8.146) and eq. (8.155). In the case of (8.146) the log-likelihood term is denoted $LL(\theta)$, whereas in the case of (8.155) the same log-likelihood term is denoted $LL(\theta | \mathcal{D})$. Does it imply that there is a typo and in (8.155) we should have $LL(\theta)$ in RHS?

**Comment by murphyk** [comment]
fixed
