### ISSUE TITLE
Section 8.7.2.1, page 308, eq. (8.156)

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#322]
It seems to me that conditioning on $\mathcal{D}$ is missing in eq. (8.156) in the RHS to make this term consistent with the notation previously employed in equations (8.155) and (8.150).

Same comment applies to the first reference to the ELBO in the first sentence of Section 8.7.2.3. Is it still the same term from equations (8.155) and (8.150)?

**Comment by murphyk** [comment]
I fixed this by removing all conditioning on D :)
