### ISSUE TITLE
Figure 10.6

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#323]
In Figure 10.6 the quality of pictures is poor, it looks like those are low-resolution .png or .jpg files. in Fig 10.6 (d) caption is cut off. In subfigures (a-c) caption is above and in (d) it is at the bottom.

I'm reading paperback printed version, so I kinda see the actual "final" quality in print.  I would like to add that the quality of pictures in the printed version is strikingly inconsistent.  For example, in my view Fig 10.2 has excellent quality, while Figure 10.4 is not great,10.6 is poor and 10.7 is excellent again. I think replacing pngs/jpgs by pdfs/vectorial throughout the book would help to significantly improve the quality of pictures.

**Comment by murphyk** [comment]
Yes I agree that figure quality could be improved. @patel-zeel  is working on this...
