### ISSUE TITLE
page 357, Section 10.5.1

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#324]
"If we set $\sigma^2 = \infty$, we force the MAP estimate to be $w = 0$"

It looks like cases $\sigma^2 = \infty$ and $\sigma^2 = 0$ are reversed in this paragraph. $\sigma^2 = \infty$ is uninformative prior, so this setting should turn MAP into MLE.

**Comment by murphyk** [comment]
this seems to be fixed already in the latest version
