### ISSUE TITLE
Wish: table of notations and symbols

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#33]
Your book does seem to use standard notation and symbols, so I'm not having trouble.

However, for utter newbies, it will be harder going for them without a table of notations and symbols used in your book.

**Comment by murphyk** [comment]
Yes I can add this to the next release. (I wrote one a while ago, but excluded it, since I didn't think it was necessary - I guess not...)

**Comment by murphyk** [comment]
just uploaded 2021-01-06 release which has notation chapter in appendix
