### ISSUE TITLE
page 573, Figure 17.8

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#332]
There is a reference to non-existent Figure 17.8(c). When discussing Figure 17.8(b), the reference to $\ell = 0.3$ is made wrongly: in the caption of Figure 17.8 it is clear that  17.8(b) corresponds to the case $\ell = 3$. Most probably, previously Figure 17.8 had 3 panes (a,b,c). Then (b) had been removed, but text discussing the figure was not adjusted accordingly.

**Comment by murphyk** [comment]
This is already fixed in 2022-04-09 version.
