### ISSUE TITLE
Page 612, Algorithm 10, typo

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#338]
In Algorithm 10, line 4, right bracket is missing before square operation under the sum

**Comment by murphyk** [comment]
I don't see the error on the latest 2022-04-09 version.
<img width="698" alt="Screen Shot 2022-04-29 at 8 23 47 PM" src="https://user-images.githubusercontent.com/4632336/166088668-f4c2777e-947b-4a3a-b34d-2e644fe786e3.png">
