### ISSUE TITLE
page 640, Section 19.3.6.1, $\theta$ parameterization

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#344]
What is $\theta$ in equation 19.30? $p(y)$ and $p(z)$ are parameterized w.r.t. $\theta$. Based on the ensuing discussion it is not clear how $p(y)$ or $p(z)$ depend on $\theta$. My understanding is that $\theta$ represent the parameters of the decoder network $f$. Does it imply that $p(y)$ and $p(z)$ are part of the decoder network?

I wonder if it could be possible to either clarify what $\theta$ is and how $p(y)$ or $p(z)$ depend on it or otherwise remove the $\theta$ parameterization in $p(y)$ and $p(z)$ to avoid confusion?

**Comment by murphyk** [comment]
fixed
