### ISSUE TITLE
Confusing statement about posterior probability (release 2021-12-31)

### ISSUE THREAD

**Issue by abdulbasitds** [probml/pml-book#35]
Hello, 

(Thankyou for the great resource)

I would like to point out the statement about posterior distribution on **Page 22, Print Version (Just before Covid example)**. Since, Bayes and posterior are very important concept for the whole book, it this might be confusing for some people(like me which are not so clever),

It says 

> Multiplying the prior by the likelihood for each value of H, and then normalizing so the result
> sums to one, gives the posterior distribution p(H = h|Y = y); this represents our new belief
> state about the possible values of H

I may be completely wrong but I am not sure how this is true. We multiply likelihood by each value of H to get **marginal likelihood** (denominator, P(Y=y)) instead and then divide by this marginal likelihood to get posterior of some p(H = h|Y = y). We dont **" multiply by each value of H in numerator(likelihood*prior) and then normalize"**

> Multiplying the prior by the "**likelihood for each value of H**", and then normalizing so the result
>  sums to one gives us 

I mean, for some specific h, to get posterior for this h i.e p(H = h|Y = y), we do not need to multiply all value of H before normalising, am i right?

**Comment by gitclem** [comment]
I will say that Bayes equation is remarkably profound given that it only has 4 terms in it!

It would be helpful to have a diagram (e.g. a rectangle) that shows how a prior probability, posterior probability, etc.

**Comment by murphyk** [comment]
I have tweaked the wording to hopefully make things clearer.

**Comment by abdulbasitds** [comment]
Thankyou @murphyk . Changes will appear in next release?

@gitclem , yeah graphical diagrams are sometime helpful.

**Comment by gitclem** [comment]
The other thing about this type of diagram, is if P(x|y) = P(x), then the diagram has just two perpendicular lines that intersect.  This is similar to the Punnett's Square (from genetics) where two genes are not "linked".

I have to confess, I couldn't wrap my head around Bayes and conditional probabilities because the image of Punnett's Square was so strong in my mind and I couldn't imagine how the picture would look if P(x|y) != P(x).
