### ISSUE TITLE
Chapter 20

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#350]
**page 703 typo**
Then we **we** can rewrite

**page 694, equation 20.126**
Error in the index of the sum, it is supposed to be $j \in nbr_i$

**page 693**
... solving the eigenvalue problem $L z_i = \lambda D z_i$ ...
First, isn't it a **generalized** eigenvalue problem?
Second, isn't $lambda$ missing an $i$ index?

**page 692 typo**
... a lower dimensional space **perserves** the reconstruction weights ...

**page 686 typo**
... it is better to use **an** bound optimization algorithm ...

**page 673, equation 20.91 typo**
The lower left block is wrong. It should be $W_y W_x^T$ and not $W_y W_y^T$.

**page 667, equation 20.68 typo**
In equation 20.68, it looks like $f(w; \theta)$ is wrong, it must be $f(z; theta)$

**page 652, figure 20.1**
I don't see a correspondence between caption and picture. Picture only contains circles, while caption references both circles and crosses. Also, caption mentions star, but I don't see a star in the picture.

**Comment by murphyk** [comment]
fixed, thanks
