### ISSUE TITLE
Chapter 21,22, 23

### ISSUE THREAD

**Issue by boreshkinai** [probml/pml-book#352]
**p 763, missing to**
"... the main goal is summarize some input data ..." -> "... the main goal is **to** summarize some input data ..." ?

**page 760, typo**
The second term is **the** used by

**page 755, typo**
using the underlying assumption **is** that

**page 754, typo**
"...similar that of words..." -> "...similar **to** that of words..." ?

**page 751, equation 23.8**
Given that $Z \in R^{|V| \times d}$, it looks like $Z^T L Z$ is a d x d matrix, which is strange as it is used as a minimization objective. I would suppose that a trace might be missing here. So the objective would look something like this $\min_{Z \in R^{|V| \times d}} tr(Z^T L Z)$. Similarly, in the paragraph following equation 23.8, I do not think that $Z^T L Z = 1/2 \sum_{i,j} W_{i,j} || Z_i -Z_j ||_2^2$ is true, because one is a matrix and the other one is a scalar. Similar comment applies to equation 20.123 in Section 20.4.9. 

A minor comment, it seems that there is extra space before Z and a space missing before "s.t." in equation 23.8.

**page 737, equation 22.7**
equation appears to be $c_i = c_i + \rho(e_{ui} - \lambda **b_i**)$, but should be $c_i = c_i + \rho(e_{ui} - \lambda **c_i**)$

**page 751 typo**
If the input is **an** weighted binary matrix

**page 709**
pairwise **disimilarity** metric

**Comment by murphyk** [comment]
fixed, thanks!
