### ISSUE TITLE
Download link broken for book1

### ISSUE THREAD

**Issue by jacobjwebber** [probml/pml-book#358]
https://github.com/probml/pml-book/releases/download/2022-05-05/book1.pdf

shows 

```
not found
```

Thanks for the excellent book!

**Comment by jacobjwebber** [comment]
A workaround (after checking the tags) is

https://github.com/probml/pml-book/releases/download/2022-04-09/book1.pdf

**Comment by murphyk** [comment]
Fixed. Renamed link to point to https://github.com/probml/pml-book/releases/latest/download/pml1.pdf.

**Comment by Helianus** [comment]
> Fixed. Renamed link to point to https://github.com/probml/pml-book/releases/latest/download/pml1.pdf.

Hello. I found this link is not working now.
