### ISSUE TITLE
Entropy is also related to information

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#36]
Section 6.1, 153 (183 of the PDF) Draft 2020-01-03

says:

> The entropy of a probability distribution can be interpreted as a measure of uncertainty, or lack
> of predictability, associated with a random variable drawn from a given distribution, as we discuss
> below.

For myself, I am always amused by the irony that this lack of predictability (entropy) is also related to information.  That is something that is completely predictable has no information.

Since the chapter is entitled "Information Theory", I think how Entropy is related to Information deserves an explanation.

In fact, even though the Chapter about Information Theory, the chapter doesn't describe much what Information is.  This will puzzle the newbie who would go by the popular definition of "information" and not the very precise one you intend.

(perhaps it's better described in your second volume?)

**Comment by murphyk** [comment]
fixed
