### ISSUE TITLE
chapter 4 page 154 last paragraph of section 4.7.4

### ISSUE THREAD

**Issue by hamed-gholami** [probml/pml-book#367]
in the second line, it is written:
In particular, we sample S datasets from theta_hat(D) and apply the...
I believe we can't sample from theta_hat of D, but instead, we can sample from the D itself. am I wrong?
thanks, BTW for your amazing book.

**Comment by murphyk** [comment]
What you are proposing is the non-parametric bootstrap, which i discuss in the following paragraph :)
