### ISSUE TITLE
Pls clarify that the aligned DNA sequences are horizontal and other issues

### ISSUE THREAD

**Issue by gitclem** [probml/pml-book#37]
Fig 6.2a p154, pdf p184 Draft 2020-01-03

People who don't know much about DNA may not realize the bases are sequential horizontally and that the columns are to compare similarity.  To clarify, I suggest changing (1st paragraph, 2nd sentence)

> (e.g., from different species)

to

> (e.g., each row is a sequence from a different species)

In addition, it would help if you had the sequence numbers at the bottom of the figure (but I'm not sure how to squeeze in 10, 11...)

```
a t a g c c g g t a c g g c a
t t a g c t g c a a c c g c a
t c a g c c a c t a g a g c a
a t a a c c g c g a c c g c a
t t a g c c g c t a a g g t a
t a a g c c t c g t a c g t a
t t a g c c g t t a c g g c c
a t a t c c g g t a c a g t a
a t a g c a g g t a c c g a a
a c a t c c g t g a c g g a a
1 2 3 4 5 6 7 8 9
```
You might even want to color the letters in 6.2a to match the colors in 6.2b

I confessed I was confused by text for Fig 6.2b:

> The overall
> vertical axis represents the information content of that location measured in bits (i.e., using log base 2).
> Deterministic distributions (with an entropy of 0) have height 2, and uniform distributions (with an entropy
> of 2) have height 0

I thought that an entropy of 0 had no information (completely deterministic), but you have bits (height) being 2.  (e.g. position 3 is always A).  On the other hand, I do understand that for a position to be highly conserved (i.e. doesn't change so that the function of the motif is preserved through evolution) is provides "information" about the importance of the position in the sequence.  E.g. positions 3,5, and 13 are critical (no variation), and positions 10 and 15 are highly important (mostly the same base.). I do see that this is explained a bit more on the next page (155), first paragraph, where you mention that the hight of the bar is 2-H_t.  Maybe because _information content_ isn't really defined in this chapter (as far as I can see.)

Finally, I note that fig 6.2b is not color blind friendly.  Prof. Jerome Friedman redid the figures in later printings of _Elements of Statistical Learning_ to account for that.

**Comment by murphyk** [comment]
I fixed the wording. I could not fix the color coding, since my old matlab code no longer runs :(
