### ISSUE TITLE
Book 1, Page 236, Confusing Integral

### ISSUE THREAD

**Issue by fengyuli2002** [probml/pml-book#376]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/76980494/172420796-07613333-23dc-4ec5-b12f-6f46c548834e.png">
 It seems dx should be at the end?

Definition from wikipedia:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/76980494/172421038-112c9131-0641-4529-b3b3-9a5ca8693e4b.png">

**Comment by murphyk** [comment]
they are both mathematically equivalent, but I have switched to the more common notation for clarity.
