### ISSUE TITLE
Book 1. Chapter 15 typos

### ISSUE THREAD

**Issue by gerdm** [probml/pml-book#377]
*  Section 15.2.8. Beam search: Incorrect values for $p(y_2 \vert y_1 =A)$. It should read, according to Figure 15.12, as $p(y_2 \vert y_1 = A) = [0.1, 0.4, 0.3, 0.2]$. Last entry in the vector is set to $0.3$
* Section 15.2.8. Beam search: incorrect values for $p(y_4\vert y_1=A, y_2=C, y_3=B)$. It should read $p(y_4\vert y_1=A, y_2=C, y_3=B) = [0.1, 0.2, 0.1, 0.6]$
* Equation (15.38) reads $\mathcal{K}(x;w) = \exp(-\frac{w^2}{2}u^2)$. It should read $\mathcal{K}(u;w) = \exp(-\frac{w^2}{2}u^2)$.

**Comment by murphyk** [comment]
fixed, thanks
