### ISSUE TITLE
Book 2: 2022-07-13, page 123, lines 21 - 25 - comment

### ISSUE THREAD

**Issue by behrman** [probml/pml-book#391]
You may wish to consider introducing the concept of Markov compatibility sooner so that readers better understand the relationship of a probability distribution and a DAG that represents it. It isn't until p. 128 that readers learn about the distinction of CI statements encoded by a graph and CI statements that hold for a distribution. On p. 123, the reader who doesn't understand this distinction may have trouble understanding how the new CI concept $\perp_G$ relates to the familiar CI concept $\perp$. [Pea09b, Definition 1.2.2] defines Markov compatibility without any mention of CI statements.

**Comment by murphyk** [comment]
good idea
