### ISSUE TITLE
convert matlab scripts to python

### ISSUE THREAD

**Issue by murphyk** [probml/pml-book#4]
Here is a list of the 74 scripts used in vol 1 that need converting:
https://docs.google.com/spreadsheets/d/1y0dmDcQnPFXZi05RFo4-MhfXYs5yQIZZy0b9wPexhig/edit#gid=0

**Comment by gerdm** [comment]
How can we contribute translating the code?

**Comment by murphyk** [comment]
Just make a pull request on the https://github.com/probml/pyprobml repo to
add your scripts.

There is a list of matlab scripts that need translating here:
https://docs.google.com/spreadsheets/d/1y0dmDcQnPFXZi05RFo4-MhfXYs5yQIZZy0b9wPexhig/edit#gid=0

The ones labeled 'diagram' just make a simple plot (eg of the sigmoid
function) and should be particularly easy to translate to python
(even if you can't read or run the matlab source).

Feel free to use standard python libraries (eg for Gaussian processes, or
sparse regression), ie no need to implement from scratch.

**Comment by gitclem** [comment]
I'm working on converting  regtreeSurfaceDemo.m to python but as a background process....

I've forgotten my MatLab and I'm busy with other things, but I should get this done eventually.

**Comment by murphyk** [comment]
moving to pyprobml contributions guidelines (WIP)
