### ISSUE TITLE
Page 70 of Book: page 100 of PDF file

### ISSUE THREAD

**Issue by aminfadaei116** [probml/pml-book#401]
In equation 2.169 I believe the integral of ( \int_{-\inf}^{y*-x1} p2(x2)dx2 ) should be on the left side of dx1.
Since if it remains on the right, the result of \int_{-\inf}^{\inf}p1(x1)dx1 will be a constant number of 1, and that doesn't make sense.

**Comment by murphyk** [comment]
fixed
