### ISSUE TITLE
Book 1 page 181 line 4 - potential typo?

### ISSUE THREAD

**Issue by mgudorf** [probml/pml-book#410]
Maybe this is just a personal preference :) 

Current:
> where $\mathbf{H}$ is the Hessian of the negative log joint $\log p(\mathcal{D}, \mathbf{\theta})$ ...

Suggestion to help it read better:
> where $\mathbf{H}$ is the Hessian of the negative log joint distribution $-\log p(\mathcal{D}, \mathbf{\theta})$ ...

or 

> where $\mathbf{H}$ is the Hessian of the negative log joint, $-\log p(\mathcal{D}, \mathbf{\theta})$, ...

**Comment by murphyk** [comment]
fixed
