### ISSUE TITLE
Book 1, version 2022-05-09, page 243, formula (7.89) - typos

### ISSUE THREAD

**Issue by behrman** [probml/pml-book#432]
In all four places:
$$\frac{\mathbf{1}_N}{N} \rightarrow \frac{\mathbf{1}_N \mathbf{1}^\top}{N}$$

**Comment by murphyk** [comment]
I defined J=1 1^trans = ones(N,N)
so we now get this
<img width="634" alt="Screen Shot 2022-07-27 at 9 45 43 PM" src="https://user-images.githubusercontent.com/4632336/181422631-1619ce7c-ca2d-45b0-84ef-7db407f4e135.png">

**Comment by behrman** [comment]
That's a good solution.
