### ISSUE TITLE
Book 2, version 2022-07-21, pages 207-208 - inconsistent notation

### ISSUE THREAD

**Issue by behrman** [probml/pml-book#435]
The notation for Bregman divergence is inconsistent:
page 207, figure 5.2(a): $D_f(\mathbf{w} \parallel \mathbf{v})$
page 207; formulas (5.68), (5.70); lines 41-42: $D_f(\mathbf{w}, \mathbf{v})$
page 207, line 37: $D_f(\mathbf{v} \parallel \mathbf{w})$
page 208, formula (5.71): $B_f(\boldsymbol{\eta}_q \parallel \boldsymbol{\eta}_p)$

Since $D_f(\mathbf{x} \parallel \mathbf{y})$ is already used for f-divergence, I recommend using $B_f(\mathbf{x} \parallel \mathbf{y})$.

**Comment by murphyk** [comment]
fixed
