### ISSUE TITLE
Book 2, version 2022-07-21, pages 208-209 - inconsistent notation

### ISSUE THREAD

**Issue by behrman** [probml/pml-book#436]
page 208, formula (5.72) uses both $\log_2$ and $\log$
page 209, formulas (5.81) and (5.82) use $\ln$, whereas formulas (5.80) and (5.83) use $\log$

To be consistent with the rest of the book, I recommend using $\log$ except for the cases where you wish to have bits with $\log_2$.

See also: page 211

**Comment by murphyk** [comment]
fixed. See also
<img width="700" alt="Screen Shot 2022-07-27 at 9 28 45 PM" src="https://user-images.githubusercontent.com/4632336/181420650-63a795f2-9d50-4721-b497-a218eacdf714.png">
