### ISSUE TITLE
Book 1, version 2022-05-09, page 252, figure 7.6 - typos

### ISSUE THREAD

**Issue by behrman** [probml/pml-book#440]
$\lambda_1^{1/2}$ -> $\lambda_1^{-1/2}$

$\lambda_2^{1/2}$ -> $\lambda_2^{-1/2}$

**Comment by murphyk** [comment]
are you sure it's wrong?
https://online.stat.psu.edu/stat505/lesson/4/4.6

**Comment by behrman** [comment]
If a multivariate normal distribution has covariance $\Sigma$ with eigenvalues $\lambda_i$, then its level sets would be those of the quadratic form defined by $\Sigma^{-1}$ with eigenvalues $\lambda_i^{-1}$.
You can also see this directly from the formula (7.163). Set $r = 1$ and $y_1 = 0$ and solve for $y_2$, similarly for $y_1$.

**Comment by murphyk** [comment]
You are right. I have finally fixed this.
