### ISSUE TITLE
Book 1, version 2022-05-09, page 257, formula (7.192) - confusing

### ISSUE THREAD

**Issue by behrman** [probml/pml-book#442]
No assumptions are made about the dimensions of $\mathbf{A}$, so it is confusing to have $\mathbf{A}^{-1}$. You may wish to consider having the last three terms of the formula in the context of square and full-rank $\mathbf{A}$ to then explain how $\mathbf{A}^\dagger$ is a generalization.

**Comment by murphyk** [comment]
fixed
