### ISSUE TITLE
Book 2, version 2022-07-21, sections 5.2-5.3 - confusing

### ISSUE THREAD

**Issue by behrman** [probml/pml-book#444]
I think your presentation may confuse readers on the concepts of cross entropy $\mathbb{H}(p, q)$ and joint entropy $\mathbb{H}(X, Y)$. You may wish to consider providing an explicit definition of joint entropy for any number of variables, and point out how you are using similar notation for two different concepts.

page 215, formula (5.106): $\mathbb{H}(XYZ)$ -> $\mathbb{H}(X, Y, Z)$

**Comment by murphyk** [comment]
fixed
