### ISSUE TITLE
Probably typo error on Page 713 (or I did not understand it fully) "R^(N×N) × R^(N×D) → R^(D×L)" should be "R^(N×N) × R^(N×D) → R^(N×L)"

### ISSUE THREAD

**Issue by atulkum** [probml/pml-book#45]
On Page 713, with section "Graph encoder network:"
"R^(N×N) × R^(N×D) → R^(D×L)" should be "R^(N×N) × R^(N×D) → R^(N×L)" or I did not get it fully.

**Comment by murphyk** [comment]
You are right, this is a typo
