### ISSUE TITLE
Book 1, Solution in pdf to 3.5

### ISSUE THREAD

**Issue by dfd** [probml/pml-book#457]
Not sure if this is the correct place to report this issue for [this](https://probml.github.io/pml-book/solns-public.pdf):

It says:
E [Y ] = E [W X] = E [X] E [X] = 0

Should say:

E [Y ] = E [W X] = E [W] E [X] = 0

**Comment by murphyk** [comment]
they look identical - what should it say?

**Comment by dfd** [comment]
I'll clarify the difference with bold font:

current:
E [Y ] = E [W X] = E [**X**] E [X] = 0

proposed:
E [Y ] = E [W X] = E [**W**] E [X] = 0

E[W] and E[X] are both 0, so the original equality is not wrong, I suppose.  Or maybe I'm not understanding how you go from E[W X] to E[X] E[X] symbolically.  But it seems more straight forward to me to move from E[W X] to E[W] E[X] (which we can do when X and W are independent) than to E[X] E[X].

Does that make sense?  Or am I missing something?

**Comment by murphyk** [comment]
Oh I see. It's just a typo. It should be `E [Y ] = E [W X] = E [W] E [X] = 0`.
