### ISSUE TITLE
Comments for Chapter 5 Optimization algorithms (January 18, 2021)

### ISSUE THREAD

**Issue by petercerno** [probml/pml-book#46]
Hi Kevin, I am sending my comments for Chapter 5 Optimization algorithms

[cerno_comments_on_pmlv2_c5.pdf](https://github.com/probml/pml-book/files/5904562/cerno_comments_on_pmlv2_c5.pdf)

Thanks!

Cheers,

Peter

**Comment by murphyk** [comment]
fixed, thanks
