### ISSUE TITLE
Book 1; version 2022-07-29; page 302; formulas, 8.109, 8.112 - comment

### ISSUE THREAD

**Issue by behrman** [probml/pml-book#463]
If formula 8.108 is considered standard form, you may wish to use the same format for formula 8.112.

Also, I think you could eliminate possible confusion by changing:
$\mathbf{A}_{eq}\boldsymbol{\theta} = \mathbf{b} _{eq}$ -> $\mathbf{C}\boldsymbol{\theta} = \mathbf{d}$

**Comment by murphyk** [comment]
good idea!
