### ISSUE TITLE
Comments for Chapter 6 Information theory (January 18, 2021)

### ISSUE THREAD

**Issue by petercerno** [probml/pml-book#47]
Hi Kevin, I am sending my comments for Chapter 6 Information theory

[cerno_comments_on_pmlv2_c6.pdf](https://github.com/probml/pml-book/files/5917211/cerno_comments_on_pmlv2_c6.pdf)

Thanks!

Cheers,

Peter

**Comment by murphyk** [comment]
fixed, thanks!
