### ISSUE TITLE
Book 1, Chapter 7, page 253 typo

### ISSUE THREAD

**Issue by mgudorf** [probml/pml-book#473]
> If $m < n$ (short, fat) and the rows of $\mathbf{A}$ are linearly independent (so $\mathbf{A}$ is full rank), then the pseudo inverse ...

I believe should be:

> (so $\mathbf{A}^{\top}$ is full rank)

unless full rank denotes row rank in this instance, but that would not seem to be consistent with the chapter's convention up to this point.

**Comment by murphyk** [comment]
fixed
