### ISSUE TITLE
Book 1, Chapter 7, page 259 footnote URL correction

### ISSUE THREAD

**Issue by mgudorf** [probml/pml-book#474]
The link to Stephen Boyd's presentation needs the extension `.pdf` in the URL, lest it return a 404 error, i.e. 

http://ee263.stanford.edu/lectures/min-norm

needs to be 

http://ee263.stanford.edu/lectures/min-norm.pdf

instead.

**Comment by murphyk** [comment]
fixed already (which version are you reading?)

**Comment by mgudorf** [comment]
Apologies for wasting time; I thought I updated my local copy but I hadn't.
