### ISSUE TITLE
Book 1, Chapter 2, page 35 typo

### ISSUE THREAD

**Issue by kanojikajino** [probml/pml-book#479]
In Section 2.1.3.5 "Independence of events",

> We say that event $A$ is **conditionally independent** of event $B$ if $\Pr(A,B)=\Pr(A)\Pr(B)$

should be

> We say that event $A$ is **independent** of event $B$ if $\Pr(A,B)=\Pr(A)\Pr(B)$

if I'm not mistaken.

**Comment by murphyk** [comment]
oops! Fixed.
