### ISSUE TITLE
Constrained optimization section

### ISSUE THREAD

**Issue by simonjdprince** [probml/pml-book#48]
Not sure what version, but downloaded and printed around 1st Feb.  Caveat: I didn't know much about this topic, so some suggestions are more to do with my understanding than anything being wrong.   Some are really pedantic as well.  Change or ignore as you see fit.

Section 5.5   boolean --> Boolean
Section 5.5.1.1  Here, you are minimizing \theta_1^2+\theta_2^2-1 but in the figure just \theta_1^2+\theta_2^2.  I know the solution is the same, but its nonetheless inconsistent.
Section 5.5.3 The description of how to convert to standard form could use some extra work.  It's not make explicit where \mathbf{A} comes from (presumably an aggregation of equations 5.106 and 5.107 but it wouldn't do any harm to say that).  Plus you do not explain how to make $\bftheta \geq \mathbf{0}$ or why this is important.
Section 5.5.3.1 In the worse case -->  In the worst-case scenario
Section 5.5.3.1 "There are various..."   This sentence is a bit of a non-sequitur and should probably be connected to the previous sentence to identify that you are saying that there do exist methods that are more efficient than the Simplex method.
Section 5.5.4 "From the geometry of the problem..."  Well, this is true, but what about when we are in 100 dimensional space and the geometry is not obvoius?
Section 5.5.6 It took me a while to figure out that NLL meant negative log likelihood having just dropped into the book here.
Section 5.6  It wasn't clear to me why we scale by \eta 
Equation 5.120  The function f() is not defined.  Possibly you mean \mathcal{L}?   The $z$ that you are argmin-ing over is also not defined.
Figure 5.15  I might be mistaken but I think you are maximizing the function in this figure vs. minimizing in Figure 5.14 which is a bit confusing.
Equation 5.131  I did not understand why there is a factor of a 1/2 on the RHS
Equation 5.132  I think the first case should be \theta-\lambda.  Something wrong anyway as this is not symmetric.
Section 5.6.3  I thought the discussion of the straight-through estimator seemed a little out of place and broke the flow.  Consider moving to end of section, shortening or dropping completely.

Realistically, I probably can't read the whole document with this level of detail, but if you know there are sections that are not well read (perhaps near the end of the book or new parts that you have added) then send me a message and I'll try to find time to focus on these.

**Comment by murphyk** [comment]
very helpful, thanks. All typos are now fixed!
