### ISSUE TITLE
Hyphen. cross-entropy, cross entropy, cross-validation, cross validation

### ISSUE THREAD

**Issue by Rajon010** [probml/pml-book#485]
All of the terms cross-entropy, cross entropy, cross-validation, and cross validation appear tens of times in book 1. It should be decided definitely whether the hyphen is needed.

**Comment by Rajon010** [comment]
At the end of chapter 8, a parenthesis is missing in the footnote.

> (see e.g., [Fra+17]

**Comment by murphyk** [comment]
Yes, I could be more consistent, but it will be too painful to fix this...
