### ISSUE TITLE
Book 1. 20220808. Chapter 5. Meaning of pi.

### ISSUE THREAD

**Issue by Rajon010** [probml/pml-book#486]
Is pi a function of a data instance or a set of data instances? Does pi output a single prediction or a (set of) model parameter(s)? Is pi a predictor or a training procedure?

![0](https://user-images.githubusercontent.com/11660172/184368823-382677e7-8df9-4ddf-98c9-0408b697fae4.jpg)
![11](https://user-images.githubusercontent.com/11660172/184368843-e3ab572e-7a2a-4f78-b6d3-a50d77565a0e.jpg)
![1](https://user-images.githubusercontent.com/11660172/184368835-d63db9c5-a8d6-4eef-bb4d-71704e27a4a5.jpg)
![2](https://user-images.githubusercontent.com/11660172/184368857-cb2a9782-3940-4bae-a1fa-f6da5f070010.jpg)
![3](https://user-images.githubusercontent.com/11660172/184368864-4c7d0d53-d289-4482-a2f3-13ff4f4069e5.jpg)
![4](https://user-images.githubusercontent.com/11660172/184368869-22574750-074b-4912-b230-27f1b97b0bc3.jpg)

**Comment by murphyk** [comment]
Yes, sorry this is not clear. Sometimes x stands for a single vector, and sometimes an entire dataset.
It depends on the context. To hopefully clarify things, I've replace D with x, to match the convention in the literature,
even though this may not match the rest of the book. I will upload a new version of this chapter soon.
