### ISSUE TITLE
Book 1. 20220808. Section 3.3.4.

### ISSUE THREAD

**Issue by Rajon010** [probml/pml-book#487]
That equality does not hold. 
Consider the univariate standard normal distribution and N=4. Suppose the sample is {-1, -1, 1, 1}. Then the joint probability density equals N(1 | mean=0, var=1) ^ 4. The probability density for the sample mean (-1 + -1 + 1 + 1) / 4 = 0 is N(0 | mean=0, var=0.25).
Grab a calculator https://www.danielsoper.com/statcalc/calculator.aspx?id=54, we have that N(1 | mean=0, var=1) ^ 4 is about 0.24 ^ 4 and N(0 | mean=0, var=0.25) is about 0.79. Obviously, they differ. 
Intuitively, the probability of a sample mean collects the probability of all possible samples having this sample mean value, and should be larger than the probability of any single such sample.
![0](https://user-images.githubusercontent.com/11660172/184473797-beaef9e8-4778-4979-be32-72388f175cf8.jpg)

**Comment by Rajon010** [comment]
Same issue in section 4.6.4.2.

**Comment by Rajon010** [comment]
Also, that N should be an exponent rather than a numerator.
![圖片](https://user-images.githubusercontent.com/11660172/188127655-7b0e934d-ebb4-4123-9c74-b0577b154dde.png)

**Comment by Rajon010** [comment]
Missing period.
![圖片](https://user-images.githubusercontent.com/11660172/188128096-bfcd63b2-dad0-4098-97b2-b9afc7ad9512.png)

**Comment by murphyk** [comment]
Re 3.65. I meant to write proportional to, not equality. See https://github.com/probml/pml-book/issues/512

**Comment by murphyk** [comment]
All fixed, thanks.
