### ISSUE TITLE
Book 1, version 2022-08-08, section 1.2.2

### ISSUE THREAD

**Issue by matt-graham** [probml/pml-book#497]
In equation (1.20) the negative log-likelihood (for the overall dataset) is defined as the mean of the negative log-likelihood terms for the individual datapoints - that is, the sum is normalized by the dataset size $N$. I think the normalization by $N$ is 'incorrect' here in the sense that the defined quantity is no longer the negative logarithm of the density of the conditional distribution on the observed data given parameters, which would correspond to the quantity in (1.20) multiplied by $N$. Removing the $\frac{1}{N}$ factor in (1.20) would also require changing the multiplier for the MSE term in (1.21) to $\frac{N}{2\sigma^2}$. Additionally, the superscript defining the upper bound of the index summed over is defined as $N_{\mathcal{D}}$ but I think should just be $N$.

**Comment by abdalgader-a** [comment]
@murphyk 
Refering to: https://github.com/probml/pml-book/issues/216.
 
 Should we write the final equation in (1.21) as:
 $NLL(\theta)  = \frac{1}{2 \sigma^2}. MSE(\theta) + Const.$ 
 or
 $NLL(\theta)  = \frac{N}{2 \sigma^2}. MSE(\theta) + Const.$
