### ISSUE TITLE
Comments for Chapter 7 Bayesian statistics [Part 1] (January 18, 2021)

### ISSUE THREAD

**Issue by petercerno** [probml/pml-book#50]
Hi Kevin, I am sending my comments for Chapter 7 Bayesian statistics [Part 1]

[cerno_comments_on_pmlv2_c7_part1.pdf](https://github.com/probml/pml-book/files/6036897/cerno_comments_on_pmlv2_c7_part1.pdf)

Thanks!

Cheers,

Peter

**Comment by murphyk** [comment]
fixed, thanks
