### ISSUE TITLE
Book 1, version 2022-08-08, section 2.8.3.1, page 67 Figure 2.19(b)

### ISSUE THREAD

**Issue by ronaldpan** [probml/pml-book#508]
![image](https://user-images.githubusercontent.com/13417382/192925932-7ccfc690-0c10-49f3-ae0e-f0a481a85af1.png)
The positions of y and y+dy should interchange.

**Comment by murphyk** [comment]
This figure is from https://blog.evjang.com/2018/01/nf1.html so hard for me to change.
However, I think it is correct (if perhaps unclear):  if $f(x) = y+dy$,
then $f(x+dx) = y$, since increasing $x$ by $dx$
should decrease the output by $dy$.)
