### ISSUE TITLE
Book1, page 90, Eq. 3.65 error?

### ISSUE THREAD

**Issue by joacorapela** [probml/pml-book#510]
I think there is a problem in Eq. 3.65 of your Probabilistic Machine Learning: and Introduction book.

Take N=2 and let y_n and z be scalars, y_1=y_2=z=0, and \Sigma_y=1.
I understand that Eq. 3.65 states:

N(y_1 | z, \Sigma_y) * N(y_2 | z, \Sigma_y) = N(\bar{y} | z, 1/2 \Sigma_y)

iff

N(0 | 0, 1) * N(0 | 0, 1) = N(0 | 0, 1/2)

iff

0.3989      * 0.3989      = 0.5642

iff

0.1591                    = 0.5642

Cordially, Joaquin

**Comment by murphyk** [comment]
I meant to say "proportional to". We are free to drop constant factors when working with likelihoods.
The proof of the statement follows from results in sec 2.2.7 of probml.github.io/book2.
In particular, let us convert to information form, where h = Sigma^{-1} z, K = Sigma^{-1} is indepdendent of z,
and g is a constant independent of y. Then we have
```
p(y1, y2 | z) = exp[ g + y1' h - 0.5 y1' K y1] * exp[ g + y2' h - 0.5 y2' K y2]
 = exp[(y1 + y2)' h] * const
 = exp[ N ybar Sigma^{-1} z] * const
 propto Gauss(ybar | z, Sigma/N)
```
