### ISSUE TITLE
Book1, page 90, Eq. 3.65 error? (follow up)

### ISSUE THREAD

**Issue by joacorapela** [probml/pml-book#512]
This issue follows up on issue #510, which was closed.

Thanks for your reply Kevin, and for the pointers to the potential functions for Gaussians.

I understand that in **Section 3.3.4** of your introductory book we want to compute the posterior $P(\mathbf{z}|\mathbf{y}_1, \ldots, \mathbf{y}_N)$, and to do this we want to isolate the components of the likelihood function that depend on $\mathbf{z}$ (and consider the remaining terms constants). This is why the proportionality in **Eq. 3.65** makes sense.

However, in the second line of your sketch of the proof of **Eq. 3.65** the term $g$ contains $\mathbf{z}$, so it should **not** be considered as a constant.

Would you agree with the following sketch of this proof:

$$\begin{aligned}
    \log p(\mathbf{y}_1|\mathbf{z})p(\mathbf{y}_2|\mathbf{z})&=K_1-\frac{1}{2}\left(\mathbf{z}^\intercal\Sigma_y^{-1}\mathbf{z}-2\mathbf{z}^\intercal\Sigma_y^{-1}\mathbf{y_1}\right)-\frac{1}{2}\left(\mathbf{z}^\intercal\Sigma_y^{-1}\mathbf{z}-2\mathbf{z}^\intercal\Sigma_y^{-1}\mathbf{y_1}\right)\\
                                                             &=K_1-\frac{1}{2}\left(\mathbf{z}^\intercal2\Sigma_y^{-1}\mathbf{z}-2\mathbf{z}^\intercal\Sigma_y^{-1}\left(\mathbf{y_1}+\mathbf{y_2}\right)\right)\\
                                                             &=K_1-\frac{1}{2}\left(\mathbf{z}^\intercal2\Sigma_y^{-1}\mathbf{z}-2\mathbf{z}^\intercal2\Sigma_y^{-1}\frac{\mathbf{y_1}+\mathbf{y_2}}{2}\right)\\
                                                             &=K_1-\frac{1}{2}\left(\mathbf{z}^\intercal2\Sigma_y^{-1}\mathbf{z}-2\mathbf{z}^\intercal2\Sigma_y^{-1}\bar{\mathbf{y}}\right)\\
                                                             &=K_2+\log\mathcal{N}(\mathbf{z}|\bar{\mathbf{y}},\frac{\Sigma_y}{2})\\                              
                                                             &=K_2+\log\mathcal{N}(\bar{\mathbf{y}}|\mathbf{z},\frac{\Sigma_y}{2})
\end{aligned}$$

**Comment by murphyk** [comment]
Yes this seems correct. Can you please send me the latex for this, and I will add it to the appendix.

**Comment by joacorapela** [comment]
Thanks for your reply Kevin, and for the willingless to take my suggestion:

> \begin{aligned}
>     \log p(\mathbf{y}_1|\mathbf{z})p(\mathbf{y}_2|\mathbf{z})&=K_1-\frac{1}{2}\left(\mathbf{z}^\intercal\Sigma_y^{-1}\mathbf{z}-2\mathbf{z}^\intercal\Sigma_y^{-1}\mathbf{y_1}\right)-\frac{1}{2}\left(\mathbf{z}^\intercal\Sigma_y^{-1}\mathbf{z}-2\mathbf{z}^\intercal\Sigma_y^{-1}\mathbf{y_1}\right)\\
>                                                              &=K_1-\frac{1}{2}\left(\mathbf{z}^\intercal2\Sigma_y^{-1}\mathbf{z}-2\mathbf{z}^\intercal\Sigma_y^{-1}\left(\mathbf{y_1}+\mathbf{y_2}\right)\right)\\
>                                                              &=K_1-\frac{1}{2}\left(\mathbf{z}^\intercal2\Sigma_y^{-1}\mathbf{z}-2\mathbf{z}^\intercal2\Sigma_y^{-1}\frac{\mathbf{y_1}+\mathbf{y_2}}{2}\right)\\
>                                                              &=K_1-\frac{1}{2}\left(\mathbf{z}^\intercal2\Sigma_y^{-1}\mathbf{z}-2\mathbf{z}^\intercal2\Sigma_y^{-1}\bar{\mathbf{y}}\right)\\
>                                                              &=K_2+\log\mathcal{N}(\mathbf{z}|\bar{\mathbf{y}},\frac{\Sigma_y}{2})\\                              
>                                                              &=K_2+\log\mathcal{N}(\bar{\mathbf{y}}|\mathbf{z},\frac{\Sigma_y}{2})
> \end{aligned}

**Comment by murphyk** [comment]
Thanks. I have updated this section (will upload soon) - new version below.

<img width="650" alt="Screenshot 2023-04-16 at 8 34 55 PM" src="https://user-images.githubusercontent.com/4632336/232371940-416e8c6f-1e3e-4b5a-b258-4145c1edb7b0.png">

**Comment by AdamJamesSheppard** [comment]
Should the second y_1 be y_2 in this derivation? Between (33) and (34) line 1.

**Comment by joacorapela** [comment]
You are right @AdamJamesSheppard I changed my latex source. Let's hope that @murphyk fixes this typo in his book. Thanks.

**Comment by joacorapela** [comment]
@murphyk last Friday I delivered a lecture (in the [probability module](https://github.com/joacorapela/gcnuBridging2023) of a summer school that we offered at the Gatsby Unit in London) covering in detail a slight extension of this problem from your book. See this [exercise](https://github.com/joacorapela/gcnuBridging2023/blob/master/probability/lectures/9_inference/inferenceInTheLinearGaussianModel/exercises/exercises.pdf) and its [solution](https://github.com/joacorapela/gcnuBridging2023/blob/master/probability/lectures/9_inference/inferenceInTheLinearGaussianModel/exercises/solutions/rapela.pdf).

In this extension I added the sample mean of the measurements as another estimator of $\mathbf{z}$. The most insightful part came from rewritting the expressions of the posterior mean and covariance to show that, as the number of observations increase, the posterior distribution is more influenced by the likelihood and less by the prior. Please refer to Eqs. 8 and 9 in the [solutions](https://github.com/joacorapela/gcnuBridging2023/blob/master/probability/lectures/9_inference/inferenceInTheLinearGaussianModel/exercises/solutions/rapela.pdf).

Also the posterior expressions show that the posterior mean and covariance converge to the sample mean and the covariance of the sample mean, which in turn converge to $\mathbf{z}$ and to the zero covariance, respectively.

Maybe this is a good point in your book to cover the distribution of the mean of independent Gaussian random vectors.
