### ISSUE TITLE
Release 2021-03-01 - Comments on Denoising Autoencoder

### ISSUE THREAD

**Issue by linker81** [probml/pml-book#52]
On Page 650 (pdf 680) - Section 20.3.2

"One useful way to control the capacity of an **(overcomplete)** autoencoder is to add noise to its input"

Even though the original work of Vincent et al., presents results on overcomplete autoencoders, the denoising criterion could be used also in undercomplete autoencoders. Is this the reason of the parentheses?

Moreover, I suggest to mention the _emphasized denoising autoencoder_ (always in the Vincent et al.). This type of DAE weights differently the errors on input's components that were corrupted and the errors on input's components that were left untouched. This approach (and its variants) is useful in the imputation data tasks.

**Comment by murphyk** [comment]
I removed the confusing (overcomplete) term. I'm not familiar with the emphasized DAE, so will omit this for now.
