### ISSUE TITLE
Book 1, version 2022-08-08, page 581

### ISSUE THREAD

**Issue by peno8** [probml/pml-book#521]
17.3 second paragraph
' The surving points are called', not sure what 'surving' is.

17.3.1 second paragraph
'than the one on the right, and intuitively is is better' , 'is' appeared 2 times.

**Comment by Rajon010** [comment]
Also section 17.3. Let me put things here.
![a](https://user-images.githubusercontent.com/11660172/205805752-96c92685-e10c-401d-99b2-0b633f90908e.jpg)
![b](https://user-images.githubusercontent.com/11660172/205805756-4f78ca6b-d2c5-45f2-94c0-896f6ebdc277.jpg)
