### ISSUE TITLE
Book 1, version 2022-08-08, section 10.2, Figure 10.5

### ISSUE THREAD

**Issue by Chenyh368** [probml/pml-book#529]
I am wondering if the code is right. The minimum of the NLL loss is probably the MLE. But from the figure we can see that the local minimum is 0. And after seeing the code, I think that we should use "return -np.mean(np.multiply(y, np.log(p).reshape(-1)) + np.multiply((1 - y), np.log(1 - p).reshape(-1)))" instead of "return -np.mean(np.multiply(y, np.log(p)) + np.multiply((1 - y), np.log(1 - p)))" to get right figure.

**Comment by murphyk** [comment]
You are right! I modified https://github.com/probml/pyprobml/blob/master/notebooks/book1/10/iris_logreg_loss_surface.ipynb, and now the loss surface has a global minimum at the mle of (w=12.9, b=-21.1). 
<img width="635" alt="Screenshot 2023-04-16 at 10 58 53 PM" src="https://user-images.githubusercontent.com/4632336/232396681-9065bcf5-debd-4854-957e-a116658128e3.png">
