### ISSUE TITLE
Thompson sampling punchline

### ISSUE THREAD

**Issue by davidrosenberg** [probml/pml-book#53]
Version: March 1, 2021, PDF page 286, book page 256.
Hey Kevin, Lihong:
In the short Thompson sampling section, you say you're using a single Monte Carlo sample as a very coarse approximation to the sampling distribution you want, and then sampling from it.  True, but I think that buries the lede.  The cool part is that sampling in this way gives you exactly the distribution you want.  

![image](https://user-images.githubusercontent.com/1561584/110062966-45587e00-7d38-11eb-9857-6a4c60c4a547.png)

Or maybe you want to leave that for an exercise...

**Comment by murphyk** [comment]
yes, that's a good point. I've updated the text.

**Comment by murphyk** [comment]
(Notationally it's a bit unclear what happened to \tilde{theta}_t in line 2
- perhaps the argument could be made more explicit by conditioning on  the
event theta=\tilde{theta}_t?)

**Comment by davidrosenberg** [comment]
What about making the variable of integration \tilde{theta}_t ?

**Comment by murphyk** [comment]
Yes, I like the idea of making the variable of integration be \tilde{theta}_t . thanks for the suggestion.
