### ISSUE TITLE
Generic LaTeX feedback

### ISSUE THREAD

**Issue by Atcold** [probml/pml-book#539]
Hi Kevin, just scrolled through very quickly and found the following $\LaTeX$ quirks.
I'd recommend `\usepackage{physics}` which gives you many useful formatting tools.

- Norms can be achieved with `\norm{}` instead of `\Vert` (if using the `physics` package). Using `||` is incorrect.
- The conditional bar is achieved with `\mid` and not `|`.
- The KL double bar is obtained with `\mathrel{\Vert}`.
- Derivatives, like `df/dx`, can be obtained with `\dv{f}{x}` (see `physics` package).
- The differential `dx` in an integral is obtained with `\dd{x}` (see `physics` package).
- `\Cref` should be used only at the beginning of a sentence. Use `\cref` within a sentence.

I'll add more when I get to flip through it a bit more.

**Comment by Atcold** [comment]
Is this good feedback? Do you want more of this type?

**Comment by murphyk** [comment]
Hi Alfredo. TBH it's not very actionable - it would take me too ling to make all these changes.
But If you find errors on specific pages, please do share. :)
