### ISSUE TITLE
Page 152, Section 4.7

### ISSUE THREAD

**Issue by mrzgh** [probml/pml-book#545]
"The basic idea (formalized in Section 4.7.1) is **to to** represent" -> "The basic idea (formalized in Section 4.7.1) is **to** represent"

**Comment by RohanKarthikeyan** [comment]
Hi. This issue has already been documented here: https://github.com/probml/pml-book/issues/515 (see the first point).

**Comment by mrzgh** [comment]
Ah sorry, I only searched the title and did not look at the content. Thanks.
