### ISSUE TITLE
Equation (7.89) typo

### ISSUE THREAD

**Issue by dogandzic** [probml/pml-book#548]
The second summand has a typo. Also, the last summand looks too complicated, can be simplified to
\frac{1^T K 1}{N^2} J.

**Comment by RohanKarthikeyan** [comment]
I think there's a 1 missing in that equation. We should have a $\frac{1}{N}\mathbf{JK}$.

**Comment by dogandzic** [comment]
Yes, that is what I meant by "The second summand has a typo."
