### ISSUE TITLE
Comments for Chapter 7 Bayesian statistics [Part 2] (February 7, 2021)

### ISSUE THREAD

**Issue by petercerno** [probml/pml-book#55]
Hi Kevin, I am sending my comments for Chapter 7 Bayesian statistics [Part 2]

[cerno_comments_on_pmlv2_c7_part2.pdf](https://github.com/probml/pml-book/files/6123271/cerno_comments_on_pmlv2_c7_part2.pdf)

Thanks!

Cheers,

Peter

**Comment by murphyk** [comment]
fixed, thanks!
