### ISSUE TITLE
Book1, P44/855, Gor06 quote

### ISSUE THREAD

**Issue by MladjanBgd** [probml/pml-book#556]
Strange lifetime calculation in quote on page 44/855:
>>And you only live for 10^9 second

I.e. 10^9 second -> 31.7 years.

**Comment by jplasser** [comment]
This is a quote that tries to quantify the order of magnitude of lifetime in powers of 10: 10^8 < lifetime < 10^10
It is not necessary to be precise to understand.

**Comment by MladjanBgd** [comment]
Of course, I was more intresetd in 10^5 bits per second as curiosity.
