### ISSUE TITLE
Release 2021-03-08

### ISSUE THREAD

**Issue by ducminhkhoi** [probml/pml-book#56]
In Section 17.3.1 (Gaussian Processes)
![image](https://user-images.githubusercontent.com/14876089/111019600-17e18500-8375-11eb-9285-1086e63a88c7.png)
Wrong formula for \mu_*,  compared to Book 0:
![image](https://user-images.githubusercontent.com/14876089/111019666-b241c880-8375-11eb-863b-a48d0d4501c3.png)

**Comment by murphyk** [comment]
Good catch! Fixed.
