### ISSUE TITLE
Book 1, version 2022-08-08, figure 15.14

### ISSUE THREAD

**Issue by RohanKarthikeyan** [probml/pml-book#564]
Consider the 2nd last layer of Figure 15.14. We have a width of 11-2+1 = 10 because we have taken a kernel width of 2. However, we only have 9 columns in the corresponding table/matrix.

Also, there are only 9 words in the sentence, "This was a great movie until ..." as opposed to 11 columns provided in the matrix and the phrase "Width: 11 words" besides it.

**Comment by murphyk** [comment]
fixed
