### ISSUE TITLE
Book 1, version 2022-08-08, page 647, section 19.4.3

### ISSUE THREAD

**Issue by zhaoyoubing** [probml/pml-book#577]
Typo in definition of f(Y) ? 

![1676897987012(1)](https://user-images.githubusercontent.com/1749030/220115709-6beb0ad3-f8b9-4d60-b0e4-511c0fff1f4e.png)

Should the right side be (according to Equation 2.16 of Houlsby's PhD dissertation "Efficient Bayesian Active Learning and Matrix Modelling")
![1676898052272(1)](https://user-images.githubusercontent.com/1749030/220115902-16814c9f-59dc-4bfd-a41c-1e8c23272496.png)

or (according to the definition of U(x) in this chapter)
![1676898096713(1)](https://user-images.githubusercontent.com/1749030/220116028-79fbc4c5-a894-4cc4-b126-cfffd6fd00d4.png)
?

**Comment by murphyk** [comment]
fixed
