### ISSUE TITLE
Book 1, version 2022-08-08, page 204, Figure 6.2 (b)

### ISSUE THREAD

**Issue by mu-arkhipov** [probml/pml-book#581]
As mentioned in the issue https://github.com/probml/pyprobml/issues/1109, the sequence logo must plot letters with total height proportional to the entropy. However, in the book the letter stack heights are just constant. The code https://github.com/probml/pyprobml/blob/auto_notebooks_md/notebooks.md#seq_logo_demo.ipynb is consistent with the picture in the book. 

I modified the notebook mentioned above to produce the correct picture (along with using `jax.numpy` instead of `numpy` following the guideline), here is the Colab link https://colab.research.google.com/drive/1ZtIihYKLv3irweYhtmwO2XhxDtMzoiKK?usp=sharing. Picture from this notebook is presented below along with the published picture. 

Current picture:
 
![seqlogo_wrong](https://user-images.githubusercontent.com/13665585/224986638-faffaaf8-eb27-4218-9dca-8bd5871c9f68.png)

Correct picture:

![seqlogo](https://user-images.githubusercontent.com/13665585/224986717-723e7d1b-2b0c-427b-8da4-6773f5bff123.png)

If everything alright, I'm ready to make a PR. However, I'm a bit uncertain on where to make changes. Is it enough to replace https://github.com/probml/pyprobml/blob/71d98dcdd3798525353eb1bfb9851b47e9d64bde/notebooks/book1/06/seq_logo_demo.ipynb ?

**Comment by murphyk** [comment]
Looks great, thanks. I added the code to https://github.com/probml/pyprobml/blob/master/notebooks/book1/06/seq_logo_demo.ipynb, and gave you credit.

**Comment by paulhorton** [comment]
A sequence logo emphasizes columns with an unexpected high degree of agreement.

For example, if using a uniform background for A,C,G,T; column 3 with all A's and column 13 with all G's should have a height of 2 bits.  

Perhaps the heights currently shown as "correct picture"  are reversed and should be subtracted from 2 to get the correct height for a sequence logo?

(A common refinement is to use a background model tuned for the organism, for example the human genome  has more A+T than C+G, in which case all G's is more surprising than all A's and so its column height would be greater.

**Comment by murphyk** [comment]
Yes, I just realized the current code is wrong. 
As Paul said (and matching https://en.wikipedia.org/wiki/Sequence_logo#Consensus_logo), the scaling should be 2-H.
The new code produces this:

<img width="644" alt="Screenshot 2023-04-16 at 8 12 11 PM" src="https://user-images.githubusercontent.com/4632336/232369100-544529d8-d67f-4f5e-be93-4942c9656790.png">
