### ISSUE TITLE
Typo in Summation of Equation (10.8) in Book 1

### ISSUE THREAD

**Issue by maxwass** [probml/pml-book#582]
I believe the upper limit of the sum in 10.8 should be $N$ not $N_{\mathcal{D}}$.

<img width="963" alt="Screenshot 2023-03-16 at 1 33 46 PM" src="https://user-images.githubusercontent.com/9613809/225704771-4ba42ba3-8ee3-44ac-bf57-a164820f9009.png">

**Comment by murphyk** [comment]
fixed
