### ISSUE TITLE
Error in Book 1, version 2023-04-17, page 674, equation 20.87

### ISSUE THREAD

**Issue by dfd** [probml/pml-book#591]
I believe the prior over p(z_n) for canonical correlation analysis should include N(z_n^y | 0, I) also.  That would match Figure 20.15.

![image](https://user-images.githubusercontent.com/2009725/233543424-33f93aee-7dd4-487c-af76-caf75d4ed925.png)

**Comment by murphyk** [comment]
fixed, thx
