### ISSUE TITLE
Typo in Book 1, version 2023-04-17, page 461, Exercise 13.1

### ISSUE THREAD

**Issue by dfd** [probml/pml-book#593]
I believe you intended to write "where _H_ is the Heaviside function" instead of "with _H_ is the Heaviside function."

![image](https://user-images.githubusercontent.com/2009725/235034014-f2ede75c-bf63-400f-b85e-30c48fe943f6.png)

**Comment by dfd** [comment]
or perhaps "with _H_ as the Heavyside function."

**Comment by murphyk** [comment]
fixed
