### ISSUE TITLE
Mismatched notation between book and solutions, Book 1, Problem 13.1

### ISSUE THREAD

**Issue by dfd** [probml/pml-book#594]
problem 13.1 in the book uses V for the weights in the second layer:
![image](https://user-images.githubusercontent.com/2009725/235386973-9793732b-0718-4519-990e-934042badfa9.png)

But the solutions use U:
![image](https://user-images.githubusercontent.com/2009725/235387021-94eca52b-5baa-4fbf-9674-c1e49cc3187f.png)

Also, the solutions use \delta_1 where the book uses \mu_2 and \delta_2 where the book uses \mu_1, although I'm not sure if that was intended or not.
![image](https://user-images.githubusercontent.com/2009725/235387199-8e44670e-78cd-44da-91bc-907112b9620d.png)

**Comment by murphyk** [comment]
Hmm, yes, that's confusing. I fixed the notation in the book (although it's not ideal that delta1 is the loss gradient  associated with layer 2...).
