### ISSUE TITLE
Punctuation Marks, Notation and Other Issues.

### ISSUE THREAD

**Issue by Wu-Xianyi-at-ECNU** [probml/pml-book#597]
1. All equations have no punctuation marks. 
2. The notation in, e.g. Chapter 20 are not consistent and may made it somewhat difficult to follow.
3. For PCA, maybe, before the algorithms,  some mathematical material of the statistical model of PCA will be helpful.

**Comment by murphyk** [comment]
Re 1. Agreed. Too late to fix this now.
Re 2. Do you have specific errors I can fix?
Re 3. PCA is usually presented as a procedure, not a model. See sec 20.2 (factor analysis) for a model-based approach.
