### ISSUE TITLE
Slight correction for last layer in learned feature extractor discussion (Book 1,  version 2023-04-17)

### ISSUE THREAD

**Issue by mboratko** [probml/pml-book#599]
On Page 12, after equation (1.29), the current text states:

> The final layer is linear and has the form $f_L(x) = w^T f_{1:L-1}(x)$ where $f_{1:L-1}(x)$ is the learned feature extractor.

however I believe what was intended was
> The final layer is linear and has the form $f_L(x) = w^T x$, so $f(x; \theta) = w^T f_{1:L-1}(x)$ where $f_{1:L-1}(x) = f_{L-1}(\cdots(f_1(x))\cdots)$ is the learned feature extractor.

(Since the functions are composed in (1.29), $f_L$ will take $f_{1:L-1}(x)$ as input.)

**Comment by murphyk** [comment]
good point. fixed, thanks
