### ISSUE TITLE
Typo in Appendix

### ISSUE THREAD

**Issue by pmkalshetti** [probml/pml-book#6]
Book Name: Probabilistic Machine Learning: An Introduction
Book date stamp: 2020-12-28
pdf page number: 749
print page number: 719

In section A.2.1 first sentence, last word should be $\mathcal{X}$ instead of $\mathcal{Y}$.

"""
A.2.1 Functions
A function f: X->Y ... for each x \in Y.
"""

**Comment by murphyk** [comment]
Fixed!

**Comment by murphyk** [comment]
fixed, thanks
