### ISSUE TITLE
Typos (Book 1, version 2023-04-17)

### ISSUE THREAD

**Issue by nihil-admirari** [probml/pml-book#601]
**p. 301**: called called KKT
![kkt](https://github.com/probml/pml-book/assets/50202386/ac6a17fd-6784-417a-9d30-7f976dd08928)

**p. 331**: foe the label
![foe](https://github.com/probml/pml-book/assets/50202386/cb1dbfdb-734a-4b80-bab9-03142f02b7ac)

**p. 377**: One can show that $0 \le R^2 \le 1$…
Maybe worth mentioning that it's not true in general, when $R^2$ is used to evaluate the performance of arbitrary models and not just linear regression?

**p. 431**:  …associated with the regular expression `*AA??CGCG??AA*`.
That's not a regex per se, rather a wildcard.

**p.435–436**:
![fwd](https://github.com/probml/pml-book/assets/50202386/37c510cd-ac05-45b1-8378-f7874299d445)
![back](https://github.com/probml/pml-book/assets/50202386/b43919b9-9dba-46a5-b861-64b484e60892)

Is it really true that forward pass is $\mathcal O(N^3)$? Seems like It's a scalar product + three matrix vector multiplications, which are $\mathcal O(N^2)$, just like the backward pass.

**p. 484**: Eq. (14.26)
![14 26](https://github.com/probml/pml-book/assets/50202386/2a794f7b-30ba-4717-8527-a1c7bad8fa87)
$w'_{c, d}$ should be inside the sum.

**p. 523**: query a given q, keys k…
![query](https://github.com/probml/pml-book/assets/50202386/af813318-8bf8-4860-9f82-8915526ce341)
Maybe “given a query $\mathbf q$, keys $\mathbf k$…”?

**p. 543**: becomes within
![becomes](https://github.com/probml/pml-book/assets/50202386/a597c51c-89c2-4d01-955c-c37808f3fdfe)

**Figure 16.5 (a)**: norm outside the box
![norm](https://github.com/probml/pml-book/assets/50202386/bba74eb5-1676-4212-9a3c-73a1d88a48df)

**Eq. (16.12)**:
![16 12](https://github.com/probml/pml-book/assets/50202386/44f326e2-69fb-4309-8e58-5d1a54169c5f)
$- \hat e_{\boldsymbol\theta}(\mathbf x)^\mathrm{T} \hat e_{\boldsymbol\theta}(\mathbf x)^+$ must be inside the exponent, otherwise (16.13) is not derivable.

**Eq (16.22)**:
![16 22](https://github.com/probml/pml-book/assets/50202386/48ca2b24-bb06-4a66-904d-54d504d92a5d)
Is it true in general? I was able to derive it only assuming balanced classes: $$\sum_{i = 1}^{N} \mathbb I(y_i = c) = \frac N C$$ for every $c$.

**p. 601**: j'the
![jthe](https://github.com/probml/pml-book/assets/50202386/7083d670-c5be-443e-ba8d-dc82122bc197)

**Table 18.1**: population minimizers not listed
![18 1](https://github.com/probml/pml-book/assets/50202386/2273614b-9a97-416d-ba2f-20a0f98cf484)

**p.616**: wjm
![wjm](https://github.com/probml/pml-book/assets/50202386/ba46376e-331a-4485-8400-1cd198276d8d)

**Comment by murphyk** [comment]
very helpful, thanks.

**Comment by nihil-admirari** [comment]
About changes made in 2023-06-23 version:

**p. 379** it we have (after $R^2$ was rewritten):
![itwe](https://github.com/probml/pml-book/assets/50202386/115c2783-dc25-4b1b-a501-1654a36a9cc1)

> Figure 16.5 (a): norm outside the box

Still outside the box.

**p. 554** Eq. (16.12) now reads
![16 12](https://github.com/probml/pml-book/assets/50202386/e3f91902-e1eb-4326-b5b0-23ae45ee6958)

I've meant
![correct16 12](https://github.com/probml/pml-book/assets/50202386/f0787dce-69d3-4085-af66-51fce45672f6)

from which eq. (16.13) is immediately derivable.
