### ISSUE TITLE
Typos (book 1, version 2023-06-23)

### ISSUE THREAD

**Issue by nihil-admirari** [probml/pml-book#606]
**Fig. 19.1**: a image images
![image images](https://github.com/probml/pml-book/assets/50202386/0a8457c1-a31a-41bd-9931-cdacc8cf257a)

**19.2.3**: an a variety
![an a variety](https://github.com/probml/pml-book/assets/50202386/2a058e64-111f-486e-9fff-5ad28323aa43)

**19.3.5**: initialize set
![initialize set](https://github.com/probml/pml-book/assets/50202386/ec7f961a-d42b-4b63-a0ca-8765e2f6a011)

**Fig. 19.11**:
lossses
![lossses](https://github.com/probml/pml-book/assets/50202386/c3a17783-904c-48a5-a49b-b40fa67bebe7)

model predictions class 0
![predictions class](https://github.com/probml/pml-book/assets/50202386/b228b419-c79e-49e9-be24-05c43649a924)

**19.3.6**: semi-supervised without a noun
![for semi-supervised](https://github.com/probml/pml-book/assets/50202386/a9b673bc-4e9f-40ad-b26d-98d9bb314c51)

**20.2.6 and other places**:
![20 2 6](https://github.com/probml/pml-book/assets/50202386/b8e55fd1-83b9-4bdb-8316-4497b7e027c1)

Nitpicking, but the book uses American spelling throughout, except for analy**s**ers. (And except for Fig.20.11.)

**20.2.6**: “let latent indicator specifying…” better be specify
![let specifying](https://github.com/probml/pml-book/assets/50202386/6836c35f-3f6a-4543-acfa-3092bdcd9a90)

In “In the special case that”, “that” is superfluous
![case that](https://github.com/probml/pml-book/assets/50202386/8ebc4c40-0aa9-4654-801c-7d51dd034d0d)

**Eq. (20.89), (20.90)**: $\mathbf B$ in equations, $\mathbf V$ in description
![B V](https://github.com/probml/pml-book/assets/50202386/633df54e-de86-4b99-a6d8-b602b6e395f1)

**Eq. (20.92)**: Should $\mathbf B$ really be absent?
![20 92](https://github.com/probml/pml-book/assets/50202386/817bb441-7ba1-468a-80d6-b7ff4f1687f2)

Direct application of (3.38) results in

$$
  \begin{bmatrix}
    \mathbf W_x \mathbf W_x^{\mathrm T} + \mathbf B_x \mathbf B_x^{\mathrm T}
      & \mathbf W_x \mathbf W_y^{\mathrm T} \\
    \mathbf W_y \mathbf W_x^{\mathrm T}
      & \mathbf W_y \mathbf W_y^{\mathrm T} + \mathbf B_y \mathbf B_y^{\mathrm T}
  \end{bmatrix}
$$

Am I doing something wrong?

**Eq. (20.111–113)** Confusing notation
![20 111](https://github.com/probml/pml-book/assets/50202386/39fbda6b-f75a-4615-be92-0ad1c6bc7968)
![20 112](https://github.com/probml/pml-book/assets/50202386/af734e3e-5d5d-4fa5-9f24-0e490a8a3a74)
![20 113](https://github.com/probml/pml-book/assets/50202386/0eb701f8-3b57-4750-b613-26265a6be135)

Is $d_{i, j}$ the same as $d_{ij}$? Should (20.112) really have $\hat d_{ij}^2$ in the denominator, while (20.111) and (20.113) are having plain $d_{ij}^2$?

**Eq. (20.133)**
![20 133](https://github.com/probml/pml-book/assets/50202386/f764892a-3fb8-42e8-9b79-7b2bc5dd6a50)

derivable only if $k \ne i$ is removed from both (20.130) and (20.131)
![20 130](https://github.com/probml/pml-book/assets/50202386/20f595a7-a5b1-4561-872b-4466bc2904b6)
![20 131](https://github.com/probml/pml-book/assets/50202386/22037334-964a-4d36-baa1-033c5bb86074)

**Eq. (20.133), (20.136)**:
![20 133](https://github.com/probml/pml-book/assets/50202386/53378346-bfba-405e-abcd-c000cb26cc11)
![20 136](https://github.com/probml/pml-book/assets/50202386/c47afba9-ae23-47b1-8d75-be68de0b31ea)

Is it really $\mathbf z_j - \mathbf z_i$ rather than the other way around? (20.138) is different
![20 138](https://github.com/probml/pml-book/assets/50202386/bd5e11c3-64fa-4693-8ce2-9c1d3124ba13)

**Eq. (20.138)**: a factor of 4 instead of 2?
![20 134-4](https://github.com/probml/pml-book/assets/50202386/680d5d85-0ed8-418c-8f0d-3fc308abfda9)

**20.5.2.2**: central (target) word to be predicted
![20 5 2 2](https://github.com/probml/pml-book/assets/50202386/40187c08-3618-46fe-927e-e3b330bb723e)

Skipgram models predict context rather than the target word.

**21.1**: data for some data
![data for data](https://github.com/probml/pml-book/assets/50202386/d546851c-cd39-4104-b53d-df1786f315ae)

**21.2.3**: and g
![and g](https://github.com/probml/pml-book/assets/50202386/0dd9cfc9-1dd9-4e00-a622-92e677ad81c5)

**21.4.1.3**: In “higher than for the other”, “for” is superfluous
![than for the other](https://github.com/probml/pml-book/assets/50202386/a40be4d9-6752-4cf7-9ace-6775dc733969)

**22.2.2**: may choosing
![may choosing](https://github.com/probml/pml-book/assets/50202386/cdad6db8-4875-43da-9393-db6e64f111aa)

**22.3**: such text
![such text](https://github.com/probml/pml-book/assets/50202386/7ecead74-b106-4c50-8049-e53de3f855bc)

**p. 749**: made **to** its
![made was](https://github.com/probml/pml-book/assets/50202386/01c67f7d-cd0f-43fb-830f-240778e45152)

**23.1**: method **to** be applicable
![to be applicable](https://github.com/probml/pml-book/assets/50202386/47136060-5950-4494-af2f-74990197816a)

**Eq. (23.6), (23.14) and may be others**: confusing notation.

(23.4) defines graph **reconstruction** and weight **regularization** losses.
![23 4](https://github.com/probml/pml-book/assets/50202386/d484f738-5f13-447b-a900-ae33f9763ed3)

In all other places, $\mathcal L_\text{G, RECON}$ is called graph **regularization** loss.
![23 6](https://github.com/probml/pml-book/assets/50202386/04e298c3-e311-4496-8a60-ce650c135c47)

**23.3.5**: maximize**s** their likelihood
![maximizes](https://github.com/probml/pml-book/assets/50202386/63724b4f-5fc3-474b-a35d-fdfd863a7451)

implication**s** **are** studied
![are studied](https://github.com/probml/pml-book/assets/50202386/7f9e9483-ddd7-47c0-bcc2-cf76ef192ace)

In “is given by … can be approximated”, “is given by” is superfluous
![is given by](https://github.com/probml/pml-book/assets/50202386/6e844b94-74d0-47bd-b6f2-240737aa9e19)

**23.5.1.2**: autoencoder**s** rely
![relies](https://github.com/probml/pml-book/assets/50202386/9c8a7fed-d46c-48d2-98a6-f7962e3247cf)

**23.5.1.4**: d**i**scriminator
![descriminator](https://github.com/probml/pml-book/assets/50202386/1813042f-3867-45bf-bb49-3a8e3303b23e)

**Eq. (23.35)**: Shouln't $\mathbf{\hat W}_{ij}$ be an outer product $\mathbf Z_i \mathbf Z_J^{\mathrm T}$?
![23 35](https://github.com/probml/pml-book/assets/50202386/5a713c72-b4b5-429e-b4a2-2fa1a79ec7cf)

**p. 767**: “… sampling process” sentence doesn't end with a period.
![no dot](https://github.com/probml/pml-book/assets/50202386/c37b3204-a777-431e-a920-dbdaee69ab7d)

**23.6.1.2**: no comma after social networks
![no comma](https://github.com/probml/pml-book/assets/50202386/7bfa4430-25dc-4908-9986-d3e18cfa246b)

**Comment by nihil-admirari** [comment]
Fig. 2.17 says
![fig](https://github.com/probml/pml-book/assets/50202386/1f91bf4a-da12-4b15-8f2f-39e984d67fe5)
which can be true only if $\mathrm{mode}\\, x = \max(\frac {a - 1} b, 0)$, but (2.142) forgets the max
![2 142](https://github.com/probml/pml-book/assets/50202386/3317f5cb-4da1-47a4-acbb-4358edbccd5f)

**Comment by murphyk** [comment]
Wow, thank you for the detailed feedback! I will incorporate it into the next update.

I  agree the denominator terms for MDS seem inconsistent. I am not sure it is correct, but FWIW, ChatGPT agrees with me.

You seem to be right about the errors in my description of tSNE. 
Based on  https://jmlr.org/papers/v9/vandermaaten08a.html, your mods are correct,
except they do include the k != i term in the denominator.
