### ISSUE TITLE
PCA Whitening Normalization Issue | Draft: 2023-06-21, Section: 7.4.5, Page: 255

### ISSUE THREAD

**Issue by berkott** [probml/pml-book#607]
It is stated that if you let [U, S, V] be the SVD of X, then you can use E = V and D = S^2 to define W_{pca} = D^{-1/2} D^T. However, this implementation misses the normalization factor of 1/N found when you get the diagonalization of the covariance as shown in the sentence before, namely, \Sigma = 1/N X^T X and with the diagonalization of \Sigma = E D E^T. 

There needs to be a 1/\sqrt{N} normalization factor somewhere. One way to do this would be to say E = 1/\sqrt{N} V and D = S^2, or to take the SVD of 1/\sqrt{N} X instead of just X.

**Comment by murphyk** [comment]
good point. fixed.
