### ISSUE TITLE
Equation 2.154 typo

### ISSUE THREAD

**Issue by waqarahmed6095** [probml/pml-book#608]
I think there is wrong substitution of P_y(y) = P_x(g(y))
![image](https://github.com/probml/pml-book/assets/54316628/792b1b72-a085-4925-a928-5d6696f5d7cc)

**Comment by srijan-mishra** [comment]
yeah but I think P_x(g(y)) = P_x(x) so that's why, what do you think @waqarahmed6095 ?

**Comment by murphyk** [comment]
fixed in another issue
