### ISSUE TITLE
Book 2. Chapter 4.3.2.1. Ising model, ground states

### ISSUE THREAD

**Issue by yurijvolkov** [probml/pml-book#610]
> If all the edge weights are positive, J > 0, then neighboring spins are likely to be in the same
state, since if xi = xj , the energy term gets a contribution of −J < 0, and lower energy corresponds
to higher probability. In the machine learning literature, this is called an associative Markov
network. In the physics literature, this is called a ferromagnetic model. **If the weights are
sufficiently strong, the corresponding probability distribution will have two modes, corresponding to
the two checkerboard patterns in Figure 4.16a**. These are called the ground states of the system.

However, according to _Information Theory, Inference, and Learning Algorithms_ (from which picture 4.16a was taken):
> The rectangular Ising model with J = 1 has two ground states, the all +1 state and the all −1 state

It aligns with intuition that if all elements of grid will be the same, the energy will be lowest => they have to be a ground state.

**Comment by murphyk** [comment]
Yes, good point. I have updated this section. See below.

<img width="457" alt="Screenshot 2024-06-12 at 4 44 09 PM" src="https://github.com/probml/pml-book/assets/4632336/4da9e668-b70a-4a04-b19e-82598fc97ac8">
