### ISSUE TITLE
Book 1, Section 1.2.2, Figure 1.7(c)

### ISSUE THREAD

**Issue by baanotdorky** [probml/pml-book#611]
It is confusing that the blue line representing the 20th-degree polynomial doesn't continue through the last observation:
<img width="220" alt="image" src="https://github.com/probml/pml-book/assets/9751447/edcc7eab-af21-4519-8cfe-241075ca85a5">

This could be fixed by expanding the range of the x-axis for the polynomial when plotting:
<img width="220" alt="image" src="https://github.com/probml/pml-book/assets/9751447/a94ee0b7-2cbc-40d5-9ee4-a4a335d4e912">

**Comment by murphyk** [comment]
fixed
<img width="639" alt="Screenshot 2024-06-12 at 8 38 30 PM" src="https://github.com/probml/pml-book/assets/4632336/3248eb26-fe09-443c-9bf8-f762f4fde912">
