### ISSUE TITLE
Book 1, Section 1.3.1, page 14, Geoff Hinton quote parenthesis Latex typo

### ISSUE THREAD

**Issue by nathan-barry** [probml/pml-book#612]
<img width="551" alt="Screenshot 2023-08-30 at 8 39 53 PM" src="https://github.com/probml/pml-book/assets/38043930/b461b858-c9e9-47a8-8d3b-a7860449ab29">

I noticed that the right parenthesis was accidentally in the superscript instead of on the outside

O(10^{14)} instead of O(10^{14}) 🤗

**Comment by murphyk** [comment]
fixed
