### ISSUE TITLE
Is this book still being written?

### ISSUE THREAD

**Issue by mdanb** [probml/pml-book#613]
I've noticed that on the book website, the pdf is called "draft," and at the bottom of many pages it says it's a draft. Is this book still being written / is it not complete yet? Or is this just for the sake of potential errors/mistakes?

**Comment by murphyk** [comment]
The book was finished in 2022. However I continue to make small edits (in response to github issues) every quarter or so. So the online version may be more up to date than the hardcopy....

**Comment by mansoorcheema** [comment]
Is the book 2nd printing hardcopy available? It seems the current available hardcopy of Amazon is 1st Printing from March 2022.
