### ISSUE TITLE
Book 1, typo in section 5.1.6.1

### ISSUE THREAD

**Issue by lee2243** [probml/pml-book#617]
at the bottom of the page, for

$q^{*}(Y|x)=\underset{q}{\mathrm{argmin}} \mathbb{H}(q(Y|x),p(Y|x))$

This is from the previous argument that optimal distribution q is found by minimizing $\mathbb{K}\mathbb{L}(p||q)$ that is, $-\mathbb{H}(p)+\mathbb{H}(p,q)$ for q. 

Since $\mathbb{H}(p)$ is constant wrt q, the optimization problem reduces to $\underset{q}{\mathrm{argmin}} \mathbb{H}(p,q)$. 

However, $\mathbb{H}(p,q) \triangleq \sum_{y\in\mathcal{Y}}p(y) \log{q(y)} \neq \mathbb{H}(q,p) \triangleq \sum_{y\in\mathcal{Y}}q(y) \log{p(y)}$.

Wouldn't the correct expression be $q^{*}(Y|x)=\underset{q}{\mathrm{argmin}} \mathbb{H}(p(Y|x),q(Y|x))$ then?

**Comment by murphyk** [comment]
Yes, you are right. Fixed, thanks.
