### ISSUE TITLE
Book 1, typo in formula 16.12, section 16.2.4.3

### ISSUE THREAD

**Issue by Vincent-Maladiere** [probml/pml-book#619]
<img width="805" alt="Screen Shot 2023-10-02 at 09 41 09" src="https://github.com/probml/pml-book/assets/18560386/fc9ffc33-fad2-44a7-a098-39cb9eb500f4">

whereas the original paper uses:

<img width="726" alt="Screen Shot 2023-10-02 at 09 43 28" src="https://github.com/probml/pml-book/assets/18560386/045f403a-0b22-432c-a3a4-4696d18a0554">

[source](https://papers.nips.cc/paper_files/paper/2016/file/6b180037abbebea991d8b1232f8a8ca9-Paper.pdf)

**Comment by murphyk** [comment]
fixed, thanks!

<img width="673" alt="Screenshot 2024-06-12 at 3 01 29 PM" src="https://github.com/probml/pml-book/assets/4632336/c06045c3-de30-41c8-9cbe-9c09992855d3">
