### ISSUE TITLE
Book 1, Figure 11.6

### ISSUE THREAD

**Issue by jdtardos** [probml/pml-book#620]
The dotted lines in Fig. 11.6 do not correspond to the diagonal, where predicted_y = true_y.

Fix: in linreg_poly_vs_degree.ipynb, substitute line:
ax.plot(ax.get_xlim(), ax.get_ylim(), ls="--", c=".3")
by:
ax.plot(ax.get_xlim(), ax.get_xlim(), ls="--", c=".3")

**Comment by murphyk** [comment]
fixed, thx
