### ISSUE TITLE
Book 1, typo in 2.154

### ISSUE THREAD

**Issue by flooreijkelboom** [probml/pml-book#623]
I believe 2.154 should be p_y (y) = d/dy P_y(y) = **d/dy P_x(g(y)) = dx/dy d/dx P_x(g(y)) = dx/dy p_x g(y))**.

**Comment by murphyk** [comment]
You are right, thanks. FIxed
<img width="482" alt="Screenshot 2024-06-12 at 12 13 37 PM" src="https://github.com/probml/pml-book/assets/4632336/0a98cd18-d4cc-4174-afbd-3b5cfd6d00cb">
