### ISSUE TITLE
Book 1, Section 2.1.3.2 Probability of a conjunction of two events - inaccuracy 

### ISSUE THREAD

**Issue by TronicLT** [probml/pml-book#626]
In the section we have the following example of independent events,

> For example, suppose X and Y are chosen uniformly at random from the set $\mathcal{X} = \{1, 2, 3, 4\}$. Let
A be the event that $X \in \{1,2\}$ and B be the event that $Y \in \{3\}$. Then we have $Pr(A, B) = Pr(A) Pr(B) =\frac{1}{2} \cdot \frac{1}{4}$

This  is incorrect,  $Pr(A, B) = 0$ as A and B are mutually exclusive. Section 2.1.3.3 correctly asserts the disjoint nature of event A and B.

**Comment by Sumit112192** [comment]
No, they are not mutually exclusive.
A is the event that $X\in {1, 2}$ and
B is the event that $Y\in {3}$

See, there are two random variables, $X$ and $Y$. Getting $X = 1$ doesn't imply that $Y = 1$. In this sense, they are both independent.

They would be mutually exclusive if 
A is the event that $X\in {1, 2}$ and
B is the event that $X\in {3}$

Now $X = 1$ would imply $X = 1$. Hence, $X \ne 3$. Hence, they are mutually exclusive. This part is explained later in the section 2.1.3.3.

@TronicLT
