### ISSUE TITLE
Book 1, Typo in equation 1.19

### ISSUE THREAD

**Issue by sunshanwen** [probml/pml-book#628]
Based on the discussion in Section 1.2.1.6, we are interested in knowing the $`\theta`$ that minimizes $`NLL(\theta)=-\frac{1}{N} \sum\limits_{n=1}^{N} \log p(y_{n}|f(x_{n};\theta))`$, therefore, we should calculate the conditional probability distribution of $` p(y|f(x;\theta))`$ rather than $` p(y_{n}|x;\theta)`$ in the left part of equation 1.19.

**Comment by murphyk** [comment]
fixed
