### ISSUE TITLE
False positive/negative reversed in Section 5.5.2, Book 1 (Ver. June 22, 2023)

### ISSUE THREAD

**Issue by ejisoo** [probml/pml-book#629]
Should be

> Hypothesis testing is a kind of binary classiﬁcation problem. As we discussed in Section 5.1.3, there are two kinds of error we can make, known as a **false positive** or type I error, which corresponds to accidentally rejecting the null hypothesis H 0 when it is true, and a **false negative** or type II error which corresponds to accidentally accepting the null when the alternative is true.

**Comment by murphyk** [comment]
Oops! Fixed, thanks
