### ISSUE TITLE
Subfigures in Figure 3.7 should be transposed

### ISSUE THREAD

**Issue by arpittiwari01** [probml/pml-book#631]
Hi Kevin,

In the paragraph attached below of section 3.2.5, row n refers to the dimensions of the n-th sample, but in Figure 3.7 (attached below), row n refers to the n-th dimension of the samples. Also, the paragraph says that 50% of the data is hidden from each row, but it should rather say that 50% is randomly hidden from the entire data.

PS: this is an incredible book, and I am learning a lot from it.

Thanks,
Arpit

![Screenshot (2)](https://github.com/probml/pml-book/assets/103291076/e7c5e43a-27f7-40d1-b931-c45b207c829f)

![Screenshot (3)](https://github.com/probml/pml-book/assets/103291076/af77f507-2a8b-4348-aa13-3b30071928b6)

**Comment by murphyk** [comment]
You are right, thanks. It's a PITA to change the figures, so I just mentioned in the caption that rows are features and columns are training examples, which is the transpose of the convention used in the text. As usual, the source of truth is the code :)
https://github.com/probml/pyprobml/blob/master/notebooks/book1/03/gauss_imputation_known_params_demo.ipynb
