### ISSUE TITLE
Book1 (June 22, 2023), 17.2.9.3 , page 582

### ISSUE THREAD

**Issue by NaifMersal** [probml/pml-book#634]
![Book1_typo0](https://github.com/probml/pml-book/assets/115889595/d994bb1c-7c1d-48f9-8fc0-f62b618f86f8)
 I think you mean Omega instead of Z 

![Book1_note](https://github.com/probml/pml-book/assets/115889595/cdda5a8f-8059-49c6-b063-9e58db796502)
 I think it's better to use Omega for notational consistency unless there is a meaning I didn't see

**Comment by murphyk** [comment]
Fixed, thanks. (I guess I switched from Z to Omega to avoid confusion with inducing points, but didn't propagate the change thoroughly enough :(
