### ISSUE TITLE
typo: Book 1 - page 705 - eq 20.144

### ISSUE THREAD

**Issue by amir-f** [probml/pml-book#635]
Book 1 - page 705 - equation 20.144 has an extra unnecessary comma

![Screenshot 2024-02-15 at 1 23 08 PM](https://github.com/probml/pml-book/assets/1664697/b9447c85-d867-47ef-b336-f775fe96f7bd)

**Comment by murphyk** [comment]
that's w', not a comma :)
But I changed it to v_i to match 20.145.
