### ISSUE TITLE
Book 1 - pag 98 - eq 3.102

### ISSUE THREAD

**Issue by younik** [probml/pml-book#637]
I think the parameters of the Bernoulli mixture models should not depend on d but only k:

<img width="257" alt="Screenshot 2024-02-19 alle 17 08 21" src="https://github.com/probml/pml-book/assets/42100908/7e946358-a92b-4325-bb47-ec6a87be07ec">

**Comment by murphyk** [comment]
No, it is correct as is, since this is a multivariate Bernoulli model, with a different mu_dk for each dimension d and cluster k.
