### ISSUE TITLE
Solutions Book: Exercise 3.5 Typo

### ISSUE THREAD

**Issue by RolandSaur** [probml/pml-book#638]
I believe there is a small typo in Exercise 3.5 question 2 of the [solutions to the book](https://probml.github.io/pml-book/solns-public.pdf).

The 3rd line should read 

> $0.5 \cdot \mathbb{E}[X\cdot -X] + 0.5 \cdot \mathbb{E}[X\cdot X]$

instead of 
> $-1 \cdot 0.5 \cdot \mathbb{E}[X\cdot -X] + 1\cdot 0.5 \cdot \mathbb{E}[X\cdot X]$

because $p(w=-1) = p(w=1) = 0.5$.

There is also two `=` on  the 4th line.

(Sidenote: Is it really necessary to show that $\mathbb{E}[Y]=0$ when $\mathbb{E}[X] =0$ -- because of $X$ ~ $\mathcal{N}(0,1)$ -- is already given.)

**Comment by murphyk** [comment]
fixed, thanks
