### ISSUE TITLE
Equation 5.84

### ISSUE THREAD

**Issue by danjenson** [probml/pml-book#639]
Currently, the book states that we can estimate the generalization gap with Equation 5.84:

```math
\mathbb{E}_{p^*}[R(f^*_N)-R(f^*)]\approx\mathbb{E}_{p_\text{tr}}[\ell(\mathbf{y}, f^*_N(\mathbf{x})]-\mathbb{E}_{p_\text{te}}[\ell(\mathbf{y},f^*_N(\mathbf{x}))]
```

However, I would expect the test loss to be higher than the training loss, which would make the RHS negative. Should the terms on the RHS be swapped?

**Comment by murphyk** [comment]
You are right. In fact there is a more serious issue in how I defined the generalization gap. This is now fixed - see below.

<img width="668" alt="Screenshot 2024-06-12 at 11 05 01 AM" src="https://github.com/probml/pml-book/assets/4632336/dead7cc8-b66c-4dde-8a9d-100f6dd9bdcd">
