### ISSUE TITLE
Potential Typo in Book 2 Chapter 10

### ISSUE THREAD

**Issue by merterden98** [probml/pml-book#643]
In book 2 chapter 10, equation 10.29 reads as:
 

\mathcal{L}(\theta, \phi | \mathcal{D}) = \sum_{n=1}^N \mathbb{E}{q\phi(z_n|x_n)} \left[ \log p_\theta(x_n, z_n) - \log q_\phi(z |x_n) \right] 

<img width="895" alt="Screenshot 2024-06-10 at 12 42 28 PM" src="https://github.com/probml/pml-book/assets/32460578/6c20b1fd-b9c7-4fe6-b97c-8556627a2748">

I would assume the z in the log q_\phi is lacking a subscript? If not what would be the reason for the omission? 

If so would this impact 10.30 as well?

**Comment by murphyk** [comment]
Yes both should be z_n. Fixed.
