### ISSUE TITLE
strange notation for MVN covariance matrix

### ISSUE THREAD

**Issue by partev** [probml/pml-book#647]
In Section 3.2.1 formula (3.16) you have the following notation:

![Screenshot 2024-06-27 15 30 44](https://github.com/probml/pml-book/assets/23830955/b0a75a86-6580-45f5-8bf5-f8659afd7898)

Only $\sigma_1^2$ and $\sigma_2^2$ are always positive $\sigma_{12}^2$ can be negative.

It is strange because it implies that $\sigma_{12}^2$ is positive while in reality if the correlation $\rho$ is negative then $\sigma_{12}^2$ is also negative implying an imaginary value for $\sigma_{12}$.

So the notation seems unhelpful.

**Comment by murphyk** [comment]
yes, good point, fixed
