### ISSUE TITLE
Book I equation 19.20

### ISSUE THREAD

**Issue by aa1234241** [probml/pml-book#649]
<img width="511" alt="Screen Shot 2024-07-16 at 2 24 08 PM" src="https://github.com/user-attachments/assets/bc33f113-888f-4e6f-bb59-4f1fe461dfa2">
should be
<img width="424" alt="Screen Shot 2024-07-16 at 2 24 23 PM" src="https://github.com/user-attachments/assets/62aefed9-850f-40f1-9382-9c55c841fcb4">

**Comment by murphyk** [comment]
fixed
