### ISSUE TITLE
Book 1 Page 200 Hypothesis Testing

### ISSUE THREAD

**Issue by siqi-zheng** [probml/pml-book#654]
I believe a negative sign is missing in the highlighted part. That is, $Pr(test(\tilde D) \leq \textbf{-test(D)}|\tilde D \sim H_0)$. Otherwise, the sum of $Pr(test(\tilde D) \geq test(D)|\tilde D \sim H_0) + Pr(test(\tilde D) \leq test(D) | \tilde D \sim H_0) = 1$. Also this assumes test(D) is positive.
<img width="575" alt="2024-08-22 160851" src="https://github.com/user-attachments/assets/97a71187-f622-412e-b53b-e4a5ee8e30e2">

**Comment by murphyk** [comment]
yes you are right, fixed
