### ISSUE TITLE
incorrect legend in Figure 18.2 (a) of supplemental materials

### ISSUE THREAD

**Issue by partev** [probml/pml-book#655]
the legend for Figure 18.2 (a) of supplemental materials says that red dots are "Mean" while the blue line is "Data". In reality it should be the opposite: red dots are "Data" while blue line is "Mean". Figure 18.2 (b) has correct legend.

![image](https://github.com/user-attachments/assets/ac082604-86f2-4b38-9eb1-961b87696add)

**Comment by murphyk** [comment]
fixed by updating https://github.com/probml/pyprobml/blob/master/notebooks/book2/18/deepgp_stepdata.ipynb
