### ISSUE TITLE
book 1, page 447, formula 13.69

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [probml/pml-book#658]
I'm sorry, but I can't understand if the dimensions of the Jacobian and of the gradient are correct.

![canccc](https://github.com/user-attachments/assets/4bcc5530-bc70-4fe2-a91b-980e8b59306e)

**Issue:
The number of columns in J_l (nl) does not match the number of rows in g_l+1 (nl+1). This mismatch means that the matrix multiplication cannot be performed directly.**

Assume the following layer dimensions:

    Layer l: nl neurons
    Layer l+1: nl+1 neurons

Given these, the shapes of the components are:

    Gradient Vector at Layer l+1:
    g_l+1 = dL / dz_l+1 
    Shape: (nl+1, 1)

    Jacobian Matrix J_l:
    J_l = dz_l+1 / dz_l 
    Shape: (nl+1, nl)

    Gradient Vector at Layer l:
    dL / dz_l 
    Shape: (nl, 1)

The formula involves multiplying J_l with g_l+1:

    J_l * g_l+1 
    Shape: (nl+1, nl) * (nl+1, 1)

**Comment by murphyk** [comment]
I don't see why g_{l+1} has shape (nl+1, 1)? I am assuming the bias term is absorbed into the weight vector (adding a dummy unit to nl as necessary).
