### ISSUE TITLE
book 1; pag. 468; Figure 14.1

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [probml/pml-book#659]
In the columns, I think that you need to add a 0 where I draw the red line, and to erase the 0 where I draw a cross.

Then maybe add "weights" and "image" or W.view(-1) @ x.view(-1) to the two different columns, and recalculate the dot product (don't know if the value is correct in the second case).

Hope that this is correct now, thanks.

![Untitled](https://github.com/user-attachments/assets/38b6106e-1b10-4ae5-a76d-f1772b241b20)

**Comment by murphyk** [comment]
unfortunately I cannot find the source of that figure so cannot make any edits.
