### ISSUE TITLE
Math error in Soln to problem 3.5: Gaussian vs jointly Gaussian

### ISSUE THREAD

**Issue by m-walters** [probml/pml-book#660]
Eq (56) in the solutions to Book 1 states 
$$E[XY] = ... = -1 \cdot 0.5 \cdot E[X \cdot -X] + 1 \cdot 0.5 \cdot E[X \cdot X] = 0$$
But I think the $-1$ and $1$ are erroneous and should not be there.

**Comment by murphyk** [comment]
you are right - fixed
