### ISSUE TITLE
Typo in Soln 3.7, Book 1

### ISSUE THREAD

**Issue by m-walters** [probml/pml-book#661]
In this sensor fusion problem, eqns 72 and 73 have elements as $\frac{v_1}{n_1}$ and $\frac{v_2}{n_2}$ for $\mathbf{\Sigma}_y^{-1}$, but these should be inversed.

<img width="909" alt="murphy_probabilistic_ml_solns pdf 2024-10-16 11-55-21" src="https://github.com/user-attachments/assets/453e3e07-b9e1-4d42-b721-ec7b10e07d6e">

**Comment by murphyk** [comment]
fixed, thanks
