### ISSUE TITLE
Implicit assumption that U's eigenvectors are orthonormal not explicitly mentioned (Book 1 - Section 20.1.3.2)

### ISSUE THREAD

**Issue by penguinness** [probml/pml-book#663]
In book 1, section 20.1.3.2, $U$ is defined to be orthogonal.
<img width="909" alt="image" src="https://github.com/user-attachments/assets/44b35b84-6be8-4bd9-8a50-4e4f5dc58abe">
However, in the calculation that follows,
<img width="329" alt="image" src="https://github.com/user-attachments/assets/fd6f9526-51a0-4850-a2dd-18d843398105">
$u_j^{T}u_j = 1$, implying $U$'s columns are not only orthogonal but also orthonormal. It would be helpful to state explicitly that $U$ is orthonormal to avoid any ambiguity, as orthogonality alone does not imply unit length.

**Comment by murphyk** [comment]
yes, good point, fixed
