### ISSUE TITLE
book 1; pag 507; 15.9

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [probml/pml-book#664]
![$Clipboard01](https://github.com/user-attachments/assets/fb63b6e3-c339-4906-bfce-51bd081d5a44)

should't it be 

p(y|x1:T ) = Cat(y|softmax(W h)) (15.9)

instead of 

p(y|x1:T ) = Cat(y|W softmax(h)) (15.9)

**Comment by murphyk** [comment]
fixed, thanks
