### ISSUE TITLE
typos in 2021-03-08 version

### ISSUE THREAD

**Issue by murphyk** [probml/pml-book#69]
Please comment on this issue if you find typos in the current version.
(Or feel free to open a separate issue if it's a big issue, like a math error.)
Remember to specify the page / section number.
Thanks!

**Comment by petercerno** [comment]
Hi Kevin, I am sending my comments for Chapter 5 Decision theory:

[cerno_comments_on_pmlv2_c5_decision_theory.pdf](https://github.com/probml/pml-book/files/6297750/cerno_comments_on_pmlv2_c5_decision_theory.pdf)

Thanks!

Cheers,

Peter

**Comment by murphyk** [comment]
thanks a lot - all fixed!
