### ISSUE TITLE
Some bugs with eq.(22.17)

### ISSUE THREAD

**Issue by Rodvi** [probml/pml-book#70]
Hello. I think there are some bugs with eq.(22.17) on p.730:
![Eq 22 17](https://user-images.githubusercontent.com/14225508/114426896-32e92400-9bc3-11eb-9b7c-2ef59ed5c41a.png)

if matrix W has D rows and K columns then it can't be multiplied by a D-dimensional column vector x. So it should be written x^T W W^T x instead of x^T W x. 

However, even if we fix this, the two expressions for f(x) will still not be equal to each other because the second sum starts from j=i+1. We should start it from j=1 if we want these two expressions to be equal.  

Finally, there is a typo - sum on v_i x_i should be from i=1, but it is written only "i=" now.

**Comment by murphyk** [comment]
thanks, fixed
