### ISSUE TITLE
Comments for Chapter 9 Linear discriminant analysis (March 8, 2021)

### ISSUE THREAD

**Issue by petercerno** [probml/pml-book#72]
Hi Kevin, I am sending my comments for Chapter 9 Linear discriminant analysis:

[cerno_comments_on_pmlv2_c9_lda.pdf](https://github.com/probml/pml-book/files/6304634/cerno_comments_on_pmlv2_c9_lda.pdf)

Thanks!

Cheers,

Peter

**Comment by murphyk** [comment]
fixed, thanks!
