### ISSUE TITLE
Section 7.2.4.1

### ISSUE THREAD

**Issue by nsanghi** [probml/pml-book#76]
Version: Draft of “Probabilistic Machine Learning: An Introduction”. March 8, 2021

equation (7.75)  \bar{x} has dimensions of 1xD

The equation (7.81) assumes \mu to have dimension Dx1. Accordingly, the text below which says \mu = \bar{x} should ideally be read as:

\mu = \bar{x}^T

or better would be equation (7.75) defines l.h.s as \bar{x}^T which would make it consistent with equation (7.84)

Further equation (7.84) is missing subscript of N 

It reads as 
$\tilda{X} = X - \bold{1}\bar{x}^T$

but it should be read as
$\tilda{X} = X - \bold{1}_N\bar{x}^T$

**Comment by murphyk** [comment]
fixed, thanks
