### ISSUE TITLE
Some typos in Chapter 1 of Book 1

### ISSUE THREAD

**Issue by ducminhkhoi** [probml/pml-book#8]
+ Page 8: the line right above Eq. (1.12): If we have "multiple inputs" => "multiple features"
+ Page 9: Eq. (1.15): should not include w^T
+ Page 11: paragraph 2: "That is, we just get observed outputs D = { y_n: n = 1 : N } without any corresponding inputs x_n." => "That is, we just get observed inputs D = { x_n: n = 1 : N } without any corresponding outputs y_n."

**Comment by murphyk** [comment]
fixed (although the choice of x vs y for unsupervised learning is debatable... I was trying to follow the tradition in statistics, where x is always a non-generated input and y is generated by the model, either conditionally or unconditionally, but the ML community may be too entrenched in their ways...)

**Comment by ronaldpan** [comment]
Page 5: under 1.2.1.4 Model fitting: The goal of supervised learing => learning

**Comment by murphyk** [comment]
fixed ronaldpan error

**Comment by murphyk** [comment]
BTW i just uploaded a new draft (tagged 2020-12-31) that fixes several other typos and cross-referencing links.

**Comment by murphyk** [comment]
fixed
