### ISSUE TITLE
Some (possible) typos in eq 2.78, fig 2.16 and around eq 2.247 - 2.148

### ISSUE THREAD

**Issue by hieuza** [probml/pml-book#80]
Please see the images for the (possible) typos. Thank you for the great book!

<img width="972" alt="Screenshot 2021-04-17 at 06 22 36" src="https://user-images.githubusercontent.com/1021144/115101904-fa8d7100-9f47-11eb-8cbe-b0a0fe6a3bc7.png">
<img width="880" alt="Screenshot 2021-04-17 at 06 30 19" src="https://user-images.githubusercontent.com/1021144/115101906-fc573480-9f47-11eb-9022-ae54f3ef95ae.png">

Figure 2.16
<img width="508" alt="Screenshot 2021-04-17 at 06 28 36" src="https://user-images.githubusercontent.com/1021144/115101907-feb98e80-9f47-11eb-8fe7-6731e3db1d40.png">

**Comment by murphyk** [comment]
fixed, thanks
