### ISSUE TITLE
Typos (March 8 version)

### ISSUE THREAD

**Issue by jmlipman** [probml/pml-book#81]
Section 4.6.2.3 Posterior
![image](https://user-images.githubusercontent.com/3540650/115137035-4b769580-a02c-11eb-907f-06721feb62cf.png)

---

Section 4.6.2.3 Posterior
![image](https://user-images.githubusercontent.com/3540650/115137045-55989400-a02c-11eb-8990-02efcd279e78.png)

---

![image](https://user-images.githubusercontent.com/3540650/115137065-6fd27200-a02c-11eb-964c-ec8e535079ce.png)

---

4.6.7.2 Example: scalar input, binary output
![image](https://user-images.githubusercontent.com/3540650/115137079-7d87f780-a02c-11eb-9acd-9db121963289.png)

---

![image](https://user-images.githubusercontent.com/3540650/115137102-98f30280-a02c-11eb-98b3-4f814c1a2831.png)

---

The one below is more of a suggestion. I would simply write 1 instead of 1.0
![image](https://user-images.githubusercontent.com/3540650/115137048-5c270b80-a02c-11eb-9eb4-9f4c9bbfce02.png)

**Comment by murphyk** [comment]
fixed, thanks
