### ISSUE TITLE
Comments for Chapter 10 Binary logistic regression (March 8, 2021)

### ISSUE THREAD

**Issue by petercerno** [probml/pml-book#82]
Hi Kevin, I am sending my comments for Chapter 10 Binary logistic regression:

[cerno_comments_on_pmlv2_c10_logreg.pdf](https://github.com/probml/pml-book/files/6365758/cerno_comments_on_pmlv2_c10_logreg.pdf)

Thanks!

Cheers,

Peter

**Comment by murphyk** [comment]
Thanks, these are very helpful. Fixed.
