### ISSUE TITLE
Missing commas in some sets in 7.1.2

### ISSUE THREAD

**Issue by djliden** [probml/pml-book#83]
Apr. 21 Version

Throughout 7.1.2, $x_1, \dots, x_n$ is sometimes presented as $x_1, \dots x_n$ (missing comma after \dots).

Example: (first set of vectors)
![image](https://user-images.githubusercontent.com/7102904/115997258-62226c80-a597-11eb-8bb4-5eb87d45827b.png)

Instances I noticed:

- First set of vectors p. 234
- Two instances in discussion of span bottom of p. 234 (eq. 7.14 and beginning of preceding paragraph)
- Second set of vectors shown on p. 235
- Second set of vectors shown in 7.1.2.5

**Comment by murphyk** [comment]
Thanks. (I probably cut and paste the original string :) Fixed.
