### ISSUE TITLE
Chapter 4: Typos

### ISSUE THREAD

**Issue by kskucheryavyy** [probml/pml-book#85]
March 8, 2021 version

1. 4.5 Regularization, page 103:
"A common way to define the complexity penalty is to use C(theta) = log p (theta)"
Shouldn't it be C(theta) = -log p(theta), since we are penalizing for a low probability prior.
In expression (4.89), the penalty term is "lambda * log p(theta)", but it seems that the correct term should be negative of that.
This would also change expression (4.90). We can then derive
![image](https://user-images.githubusercontent.com/83252212/116165243-6afd7480-a736-11eb-940f-e65197e8bbb6.png)

2. 4.6.6 Credible Intervals, page 127:
"This motivates an alternative quantity known as the highest posterior density or HPD regionm..."
regionm -> region

3. 4.6.7.1 Plugin approximation, page 129, Expression (4.192):
Shouldn't it be conditional on **x**?
![image](https://user-images.githubusercontent.com/83252212/116164838-7a2ff280-a735-11eb-9fee-94ec4b8f8698.png)

4. 4.6.7.2 Example: scalar input, binary output, page 130:
"The decision boundary is is defined to be the input"
-> "is" is repeated twice 

5. 4.6.7.2 Example: scalar input, binary output, page 129, expression (4.195):
![image](https://user-images.githubusercontent.com/83252212/116166903-ffb5a180-a739-11eb-8088-d0f4282449f1.png)
Needs to be "-b" in the exponent

6. 4.6.7.2 Example: scalar input, binary output, page 129:
Inconsistent use of "," versus ";" in the conditional part of probabilities in expressions (4.193)-(4.196)

7. 4.6.8.4 Markov Chain Monte Carlo (MCMC) approximation, page 134:
"Although VI is a fast, optimization-based mthod"
mthod -> method

**Comment by jmlipman** [comment]
More typos.

![image](https://user-images.githubusercontent.com/3540650/116453239-4e148e80-a867-11eb-87d9-201b2497a69f.png)

**Section 4.7.2**
![image](https://user-images.githubusercontent.com/3540650/116453283-5c62aa80-a867-11eb-8f5b-5b8b450fa944.png)

**Section 5.1.1**
![image](https://user-images.githubusercontent.com/3540650/116453344-6f757a80-a867-11eb-946f-4da579e29db2.png)

![image](https://user-images.githubusercontent.com/3540650/116453405-83b97780-a867-11eb-956d-c687929650d2.png)

![image](https://user-images.githubusercontent.com/3540650/116453430-8b791c00-a867-11eb-8cdf-ac592ca3a37d.png)

![image](https://user-images.githubusercontent.com/3540650/116453469-992ea180-a867-11eb-8966-d4fa63905232.png)

![image](https://user-images.githubusercontent.com/3540650/116453490-a055af80-a867-11eb-8bb3-b72ba897db8f.png)

![image](https://user-images.githubusercontent.com/3540650/116453522-a8adea80-a867-11eb-80b9-049d6fa6f3c0.png)

**Section 5.2.2**
I guess N = 100,000, and find -> found
![image](https://user-images.githubusercontent.com/3540650/116453587-b82d3380-a867-11eb-8007-75e9c519f6ed.png)

**Comment by rajkirankv** [comment]
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/11528844/116468823-35d04f80-a826-11eb-88a5-0b159979f086.png">
$\beta \in [0, 1]$

**Comment by murphyk** [comment]
Thanks, everyone! All fixed.
