### ISSUE TITLE
Release 2020-12-31 Typo

### ISSUE THREAD

**Issue by briansmlee** [probml/pml-book#9]
print page 392 pdf 422 "convolutional neural networks (CNN), which are designed to work with variable-sized **~and~** images;"

print 393 pdf 423 "However, suppose we **~replacing~ replace** the Heaviside function"

print 400 pdf 430 "it can be used to model financial data, **~we~ as** well as the global temperature of the earth"

**Comment by mellorjc** [comment]
p233  8.1.1 "they have ~~**sever**~~ **severe** cancer."

p235  8.1.2.3 "the optimal action is to pick the reject action if the most probable class has a probability ~~**above**~~ **below** λ"

**Comment by shoyer** [comment]
print page 454, pdf page 484: "and **~initializ~ initialize** from the content"

**Comment by morteza** [comment]
print page 156, pdf page 186: "If Y is a deterministic function of ~**Y**~ **X** so that knowing X completely ~**determinies**~ **determines** Y"

**Comment by MetlHedd** [comment]
print page 23, pdf page 53: "TNR is true negative rate, TPR is true positive rate, FNR is false negative
rate, ~TPR is true positive rate~ FPR is false positive rate."

**Comment by mcallara** [comment]
print page 210, pdf page 240: "directly, ~as~ as shown" 
print page 252, pdf page 282: "this is known ~as~ as the Gittins"

**Comment by pwroberts** [comment]
Print page 5, PDF page 35, §1.2.1.3: "Points lying to the left of this
boundary are classified as setosa; points to the right are either versicolor or ~virgnica~ virginica."

**Comment by bsrthyle** [comment]
print page 22 PDF 
We want to compute p(H = h|Y = y), for h ∈ {0, 1}, where ~~x~~ h is the observed test outcome.

**Comment by Kumru** [comment]
print page 161, pdf page 191: "the optimal _q_ by ~~consider~~ considering inputs _x_ for which"

**Comment by Kumru** [comment]
print page 161-162, pdf page 191-192, §6.2.6, there are inconsistencies in the definitions of the KL divengences.

**Comment by murphyk** [comment]
I have fixed all the above issues. I will upload a new version later today.

**Comment by kamalesh0406** [comment]
Print page 34, §2.3.2.4: "we see that there is a broad ~~generalizatino~~ generalization gradient, which extends further along the vertical dimension"
Print page 35, §2.3.2.4: "This is because the data has a broader vertical spread than ~~horizonta~~ horizontal."

**Comment by NiklasTR** [comment]
page 6 in the pdf: One way to define the problem of model fitting or training is to find a setting of the **paramters**

**Comment by linker81** [comment]
Print Page 589, PDF Page 619: "A natural approach to ~~transfer learning~~ meta-learning"

**Comment by abdulbasitds** [comment]
Can anyone please tell how to find the release stamp/date of the version I have (its 2021 edition). I wanted to report/clearify one thing.

**Comment by ducminhkhoi** [comment]
> Can anyone please tell how to find the release stamp/date of the version I have (its 2021 edition). I wanted to report/clearify one thing.

you can follow this: 
![image](https://user-images.githubusercontent.com/14876089/103684447-6bcc8980-4f40-11eb-95f8-14313617104f.png)

**Comment by murphyk** [comment]
all fixed in latest release
