### ISSUE TITLE
Comments on section 13.1

### ISSUE THREAD

**Issue by danoneata** [probml/pml-book#90]
Hello! Thank you for providing such a valuable and comprehensive resource!

Here are some comments on section 13.1 from the April 21, 2021 version:

- On page 439, line 3, in the equation `p(y|x,w) = Cat(y|S(Wx))`, the parameter on the left-hand side should also be denoted by a capital letter—`W` instead of `w`.
- Equation (13.1) is missing a closing bracket.
- Instead of `g^{-1}()` is probably enough to use `g^{-1}` (the first notation denotes "calling" the inverse function).
- I would define `Θ = (W, b)` after Equation (13.2).
- The semantics of `Θ` are potentially confusing in Equations (13.4) and (13.5): in Equation (13.4), `Θ` contains part of the parameters, `Θ = (W, b)`, while in Equation (13.5), `Θ` contains all the parameters, `Θ = (Θ₁, Θ₂, ...)`.
- The phrase "DAG (directed acyclic graph)" should probably be "directed acyclic graph (DAG)", in order to be consistent with the rest of the text.
- Maybe "very" is somewhat overused: "very restrictive", "very limiting"?

**Comment by murphyk** [comment]
thanks, fixed
