### ISSUE TITLE
Structured vs unstructured data

### ISSUE THREAD

**Issue by aciobanusebi** [probml/pml-book#91]
![image](https://user-images.githubusercontent.com/17072091/117126712-d59c5900-ada3-11eb-95d4-72fa7a9c2c73.png)
Is this correct? I've always thought of images/sounds/videos/etc. as unstructured data, and of tables (which are fed into MLPs) as structured data. Reference: https://cs230.stanford.edu/files/C1M1.pdf
![image](https://user-images.githubusercontent.com/17072091/117127222-7ab73180-ada4-11eb-84b6-ab08e8cce0ad.png)

Excuse me if I got it wrong!

**Comment by murphyk** [comment]
That's an interesting point. Some authors do use the term "structured data"
to refer to tabular data, and treat images and text as unstructured.
I will adjust my wording accordingly to avoid confusion.
