### ISSUE TITLE
Linearity of expectation

### ISSUE THREAD

**Issue by nsanghi** [probml/pml-book#92]
ver: Draft of “Probabilistic Machine Learning: An Introduction”. April 21, 2021

Equation 2.26 - Page 38 of the book

The text before eqn 2.26 says: 
"For a set of n independent random variables, one can show that the expectation of their sum and product is as follows:"

Is not the equation 2.26 true even for dependent variables? It is a minor point but I thought I will just point out for correctness sake

Equation 2.27 as given is true only for independent variables. But equation 2.26 is more general.

**Comment by murphyk** [comment]
good catch, thx
