### ISSUE TITLE
Inconsistent notation for regularized empirical risk in chapters 4 and 5

### ISSUE THREAD

**Issue by shaabhishek** [probml/pml-book#98]
ver: Draft of “Probabilistic Machine Learning: An Introduction”. May 6, 2021

Not sure if this was intended (or really serious) but chapter 4 introduces regularized empirical risk as:

![image](https://user-images.githubusercontent.com/6151272/117589381-f1726880-b0dd-11eb-99ad-b9d152b9213c.png)

while chapter 5 introduces it with the reversed arguments for parameters and data:

![image](https://user-images.githubusercontent.com/6151272/117589408-22529d80-b0de-11eb-870f-a0222da357ec.png)

**Comment by murphyk** [comment]
fixed, thanks
